// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../../index.js";

export interface ListPollingWebhooksResponse {
    count: AgentMail.Count;
    limit?: AgentMail.Limit;
    nextPageToken?: AgentMail.PageToken;
    /**
     * Ordered by `created_at` descending. Lists the subscriptions created through this route
     * (organization, pod, or inbox); subscriptions created through a pod or inbox route are listed
     * through that route.
     */
    pollingWebhooks: AgentMail.webhooks.PollingWebhook[];
}
