// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../../../index.js";

/**
 * @example
 *     {
 *         startTimestamp: new Date("2024-01-15T09:30:00.000Z"),
 *         endTimestamp: new Date("2024-01-15T09:30:00.000Z")
 *     }
 */
export interface ListInboxMetricsRequest {
    eventTypes?: AgentMail.MetricEventTypes;
    startTimestamp: AgentMail.MetricStartTimestamp;
    endTimestamp: AgentMail.MetricEndTimestamp;
}
