// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../../../index.js";

/**
 * @example
 *     {}
 */
export interface QueryEventsRequest {
    eventTypes?: AgentMail.MetricEventTypes;
    start?: AgentMail.Start;
    end?: AgentMail.End;
    period?: AgentMail.Period;
    limit?: AgentMail.MetricLimit;
    descending?: AgentMail.Descending;
}
