// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

/**
 * List of metric event types to query.
 */
export type MetricEventTypes = AgentMail.MetricEventType[];
