// This file was auto-generated by Fern from our API Definition.

/**
 * Type of rate. `bounce` is bounced messages divided by messages sent,
 * counting permanent and transient bounces; `complaint` is spam complaints
 * divided by messages sent.
 */
export const RateType = {
    Bounce: "bounce",
    Complaint: "complaint",
} as const;
export type RateType = (typeof RateType)[keyof typeof RateType];
