// This file was auto-generated by Fern from our API Definition.

/**
 * How often a point is sampled, as a whole number of seconds between 60
 * and 86400. Defaults to 3600 (one point per hour).
 */
export type RatePeriod = number;
