// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

/**
 * List of usage metric types to query. Omit to query every type valid for the scope.
 */
export type UsageTypes = AgentMail.UsageType[];
