/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as AgentMail from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { EventType } from "../../../types/EventType";
import { EventId } from "./EventId";
import { Message } from "../../../../messages/types/Message";

export const MessageReceivedPayload: core.serialization.ObjectSchema<
    serializers.webhooks.MessageReceivedPayload.Raw,
    AgentMail.webhooks.MessageReceivedPayload
> = core.serialization.object({
    eventType: core.serialization.property("event_type", EventType),
    eventId: core.serialization.property("event_id", EventId),
    message: Message,
});

export declare namespace MessageReceivedPayload {
    export interface Raw {
        event_type: EventType.Raw;
        event_id: EventId.Raw;
        message: Message.Raw;
    }
}
