/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index.js";
import * as AgentMail from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import { EventType } from "../../../types/EventType.js";
import { EventId } from "./EventId.js";
import { Complaint } from "./Complaint.js";

export const MessageComplainedPayload: core.serialization.ObjectSchema<
    serializers.webhooks.MessageComplainedPayload.Raw,
    AgentMail.webhooks.MessageComplainedPayload
> = core.serialization.object({
    eventType: core.serialization.property("event_type", EventType),
    eventId: core.serialization.property("event_id", EventId),
    complaint: Complaint,
});

export declare namespace MessageComplainedPayload {
    export interface Raw {
        event_type: EventType.Raw;
        event_id: EventId.Raw;
        complaint: Complaint.Raw;
    }
}
