/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index.js";
import * as AgentMail from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";

export const SvixId: core.serialization.Schema<serializers.webhooks.SvixId.Raw, AgentMail.webhooks.SvixId> =
    core.serialization.string();

export declare namespace SvixId {
    export type Raw = string;
}
