// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

export interface Reject {
    inboxId: AgentMail.inboxes.InboxId;
    threadId: AgentMail.ThreadId;
    messageId: AgentMail.MessageId;
    timestamp: AgentMail.Timestamp;
    /** Reject reason. */
    reason: string;
}
