/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../../../../../index";

export interface Attachment {
    attachmentId: AgentMail.inboxes.AttachmentId;
    filename: AgentMail.inboxes.AttachmentFilename;
    contentType: AgentMail.inboxes.AttachmentContentType;
    size: AgentMail.inboxes.AttachmentSize;
    inline: AgentMail.inboxes.AttachmentInline;
}
