/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../../../../../index";

export interface Message {
    inboxId: AgentMail.inboxes.InboxId;
    threadId: AgentMail.inboxes.ThreadId;
    messageId: AgentMail.inboxes.MessageId;
    eventId: AgentMail.inboxes.MessageEventId;
    labels: AgentMail.inboxes.MessageLabels;
    timestamp: AgentMail.inboxes.MessageTimestamp;
    from: AgentMail.inboxes.MessageFrom;
    to: AgentMail.inboxes.MessageTo;
    cc?: AgentMail.inboxes.MessageCc;
    bcc?: AgentMail.inboxes.MessageBcc;
    subject?: AgentMail.inboxes.MessageSubject;
    preview?: AgentMail.inboxes.MessagePreview;
    text?: AgentMail.inboxes.MessageText;
    html?: AgentMail.inboxes.MessageHtml;
    attachments?: AgentMail.inboxes.MessageAttachments;
    inReplyTo?: AgentMail.inboxes.MessageInReplyTo;
    references?: AgentMail.inboxes.MessageReferences;
}
