/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const ThreadPreview: core.serialization.Schema<serializers.ThreadPreview.Raw, AgentMail.ThreadPreview> =
    core.serialization.string();

export declare namespace ThreadPreview {
    export type Raw = string;
}
