/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const ThreadSentTimestamp: core.serialization.Schema<
    serializers.ThreadSentTimestamp.Raw,
    AgentMail.ThreadSentTimestamp
> = core.serialization.date();

export declare namespace ThreadSentTimestamp {
    export type Raw = string;
}
