/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as AgentmailApi from "../../../../api/index";
import * as core from "../../../../core";

export const ThreadPreview: core.serialization.Schema<serializers.ThreadPreview.Raw, AgentmailApi.ThreadPreview> =
    core.serialization.string().optional();

export declare namespace ThreadPreview {
    export type Raw = string | null | undefined;
}
