// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ThreadReceivedTimestamp: core.serialization.Schema<
    serializers.ThreadReceivedTimestamp.Raw,
    AgentMail.ThreadReceivedTimestamp
> = core.serialization.date();

export declare namespace ThreadReceivedTimestamp {
    export type Raw = string;
}
