// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ThreadCreatedAt: core.serialization.Schema<serializers.ThreadCreatedAt.Raw, AgentMail.ThreadCreatedAt> =
    core.serialization.date();

export declare namespace ThreadCreatedAt {
    export type Raw = string;
}
