// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ThreadId } from "./ThreadId.js";
import { ThreadLabels } from "./ThreadLabels.js";

export const UpdateThreadResponse: core.serialization.ObjectSchema<
    serializers.UpdateThreadResponse.Raw,
    AgentMail.UpdateThreadResponse
> = core.serialization.object({
    threadId: core.serialization.property("thread_id", ThreadId),
    labels: ThreadLabels,
});

export declare namespace UpdateThreadResponse {
    export interface Raw {
        thread_id: ThreadId.Raw;
        labels: ThreadLabels.Raw;
    }
}
