// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

export interface PodListListEntriesResponse {
    count: AgentMail.Count;
    limit?: AgentMail.Limit;
    nextPageToken?: AgentMail.PageToken;
    /** Ordered by entry ascending. */
    entries: AgentMail.PodListEntry[];
}
