// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

export interface Attendee {
    /** Email address of the attendee. Stored in lowercase. Must be unique within the event. */
    email: string;
    /** Display name of the attendee. At most 256 characters. */
    name?: string;
    /** Response status. Defaults to `needs_action`. */
    status?: AgentMail.AttendeeStatus;
    /** Defaults to `required`. */
    role?: AgentMail.AttendeeRole;
    /**
     * Comment the attendee sent with their response. At most 4,096 UTF-8 bytes; on create or
     * update, a longer comment is dropped rather than rejected.
     */
    comment?: string;
    /** Time at which the attendee last responded. */
    respondedAt?: Date;
}
