// This file was auto-generated by Fern from our API Definition.

/**
 * Read consistency. `eventual` (default) reads from the region that serves your request and may
 * lag a write made moments earlier by up to a few seconds. `primary` reads from the primary region
 * and always reflects every completed write.
 */
export const CalendarConsistency = {
    Eventual: "eventual",
    Primary: "primary",
} as const;
export type CalendarConsistency = (typeof CalendarConsistency)[keyof typeof CalendarConsistency];
