// This file was auto-generated by Fern from our API Definition.

/**
 * ID of an accepted deletion. While the event is being removed, retrying the same delete (with the
 * same `Idempotency-Key`, or none and the same `send_invites`) returns it again. Once removal has
 * finished, a retry returns `404`.
 */
export type DeletionId = string;
