// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

export interface ListCalendarEventsResponse {
    count: AgentMail.Count;
    limit: AgentMail.Limit;
    nextPageToken?: AgentMail.PageToken;
    /**
     * On List Events, ordered by `updated_at` descending. On Get Agenda and List Event Instances,
     * ordered by `start_at` ascending.
     */
    events: AgentMail.CalendarEvent[];
}
