// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

/**
 * A wall-clock date or date-time, or (timed events only) a period.
 */
export type RecurrenceDate = AgentMail.WallTime | AgentMail.RecurrencePeriod;
