// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

/**
 * Send only the fields to change. Fields set to `null` are cleared. At least one field is required.
 * `all_day`, `timezone` and `recurrence` can only be changed on a one-off or series UUID, not on a
 * dated event ID.
 */
export interface UpdateCalendarEventRequest {
    title?: string;
    /** Set to `null` to clear. */
    description?: string | null;
    /** Set to `null` to clear. */
    location?: string | null;
    /** Replaces the metadata (any JSON value, usually an object). Set to `null` to clear. */
    metadata?: unknown | null;
    status?: AgentMail.CalendarEventStatus;
    /** Changing `all_day` requires `start`, `end` and `timezone` in the same request. Not accepted for dated event IDs. */
    allDay?: boolean;
    /** New start. For a one-off or series UUID, send it together with `end`. Not accepted with `mode=future`. */
    start?: AgentMail.WallTime;
    /** New end. For a one-off or series UUID, send it together with `start`. A dated ID accepts `end` alone. */
    end?: AgentMail.WallTime;
    /** New time zone. Not accepted for dated event IDs. */
    timezone?: AgentMail.IanaTimezone;
    durationMode?: AgentMail.DurationMode;
    /**
     * Replaces the recurrence. Set to `null` to turn a series into a one-off event (only when no
     * date of it has been edited). Not accepted for dated event IDs.
     */
    recurrence?: AgentMail.RecurrenceInput | null;
    /** Replaces the attendee list. */
    attendees?: AgentMail.Attendee[];
    /**
     * When `true`, emails the updated invitation to every attendee. Only the organizer (an `api`
     * event) can send. Defaults to `false`.
     */
    sendInvites?: boolean;
}
