// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const DraftId: core.serialization.Schema<serializers.DraftId.Raw, AgentMail.DraftId> =
    core.serialization.string();

export declare namespace DraftId {
    export type Raw = string;
}
