/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const DraftReplyTo: core.serialization.Schema<serializers.DraftReplyTo.Raw, AgentMail.DraftReplyTo> =
    core.serialization.list(core.serialization.string());

export declare namespace DraftReplyTo {
    export type Raw = string[];
}
