// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { InboxId } from "../../inboxes/types/InboxId.js";
import { ThreadId } from "../../threads/types/ThreadId.js";
import { DraftAttachments } from "./DraftAttachments.js";
import { DraftBcc } from "./DraftBcc.js";
import { DraftCc } from "./DraftCc.js";
import { DraftClientId } from "./DraftClientId.js";
import { DraftHtml } from "./DraftHtml.js";
import { DraftId } from "./DraftId.js";
import { DraftInReplyTo } from "./DraftInReplyTo.js";
import { DraftLabels } from "./DraftLabels.js";
import { DraftPreview } from "./DraftPreview.js";
import { DraftReplyTo } from "./DraftReplyTo.js";
import { DraftSendAt } from "./DraftSendAt.js";
import { DraftSendStatus } from "./DraftSendStatus.js";
import { DraftSubject } from "./DraftSubject.js";
import { DraftText } from "./DraftText.js";
import { DraftTo } from "./DraftTo.js";
import { DraftUpdatedAt } from "./DraftUpdatedAt.js";

export const Draft: core.serialization.ObjectSchema<serializers.Draft.Raw, AgentMail.Draft> = core.serialization.object(
    {
        inboxId: core.serialization.property("inbox_id", InboxId),
        threadId: core.serialization.property("thread_id", ThreadId),
        draftId: core.serialization.property("draft_id", DraftId),
        clientId: core.serialization.property("client_id", DraftClientId.optional()),
        labels: DraftLabels,
        replyTo: core.serialization.property("reply_to", DraftReplyTo.optional()),
        to: DraftTo.optional(),
        cc: DraftCc.optional(),
        bcc: DraftBcc.optional(),
        subject: DraftSubject.optional(),
        preview: DraftPreview.optional(),
        text: DraftText.optional(),
        html: DraftHtml.optional(),
        attachments: DraftAttachments.optional(),
        inReplyTo: core.serialization.property("in_reply_to", DraftInReplyTo.optional()),
        references: core.serialization.list(core.serialization.string()).optional(),
        sendStatus: core.serialization.property("send_status", DraftSendStatus.optional()),
        sendAt: core.serialization.property("send_at", DraftSendAt.optional()),
        updatedAt: core.serialization.property("updated_at", DraftUpdatedAt),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
    },
);

export declare namespace Draft {
    export interface Raw {
        inbox_id: InboxId.Raw;
        thread_id: ThreadId.Raw;
        draft_id: DraftId.Raw;
        client_id?: DraftClientId.Raw | null;
        labels: DraftLabels.Raw;
        reply_to?: DraftReplyTo.Raw | null;
        to?: DraftTo.Raw | null;
        cc?: DraftCc.Raw | null;
        bcc?: DraftBcc.Raw | null;
        subject?: DraftSubject.Raw | null;
        preview?: DraftPreview.Raw | null;
        text?: DraftText.Raw | null;
        html?: DraftHtml.Raw | null;
        attachments?: DraftAttachments.Raw | null;
        in_reply_to?: DraftInReplyTo.Raw | null;
        references?: string[] | null;
        send_status?: DraftSendStatus.Raw | null;
        send_at?: DraftSendAt.Raw | null;
        updated_at: DraftUpdatedAt.Raw;
        created_at: string;
    }
}
