/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";

export const DraftTo: core.serialization.Schema<serializers.DraftTo.Raw, AgentMail.DraftTo> = core.serialization.list(
    core.serialization.string(),
);

export declare namespace DraftTo {
    export type Raw = string[];
}
