// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const DraftUpdatedAt: core.serialization.Schema<serializers.DraftUpdatedAt.Raw, AgentMail.DraftUpdatedAt> =
    core.serialization.date();

export declare namespace DraftUpdatedAt {
    export type Raw = string;
}
