// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Attachment } from "../../attachments/types/Attachment.js";

export const DraftAttachments: core.serialization.Schema<serializers.DraftAttachments.Raw, AgentMail.DraftAttachments> =
    core.serialization.list(Attachment);

export declare namespace DraftAttachments {
    export type Raw = Attachment.Raw[];
}
