// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import type * as AgentMail from "../index.js";

export class IsTakenError extends errors.AgentMailError {
    constructor(body: AgentMail.ErrorResponse, rawResponse?: core.RawResponse) {
        super({
            message: "IsTakenError",
            statusCode: 403,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = this.constructor.name;
    }
}
