/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as AgentMail from "../index";

export class IsTakenError extends errors.AgentMailError {
    constructor(body: AgentMail.ErrorResponse) {
        super({
            message: "IsTakenError",
            statusCode: 403,
            body: body,
        });
        Object.setPrototypeOf(this, IsTakenError.prototype);
    }
}
