// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";
import { Count } from "../../../../../types/Count.js";
import { Limit } from "../../../../../types/Limit.js";
import { PageToken } from "../../../../../types/PageToken.js";
import { PollingWebhook } from "./PollingWebhook.js";

export const ListPollingWebhooksResponse: core.serialization.ObjectSchema<
    serializers.webhooks.ListPollingWebhooksResponse.Raw,
    AgentMail.webhooks.ListPollingWebhooksResponse
> = core.serialization.object({
    count: Count,
    limit: Limit.optional(),
    nextPageToken: core.serialization.property("next_page_token", PageToken.optional()),
    pollingWebhooks: core.serialization.property("polling_webhooks", core.serialization.list(PollingWebhook)),
});

export declare namespace ListPollingWebhooksResponse {
    export interface Raw {
        count: Count.Raw;
        limit?: Limit.Raw | null;
        next_page_token?: PageToken.Raw | null;
        polling_webhooks: PollingWebhook.Raw[];
    }
}
