// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const AgentAttachHumanResponse: core.serialization.ObjectSchema<
    serializers.AgentAttachHumanResponse.Raw,
    AgentMail.AgentAttachHumanResponse
> = core.serialization.object({
    humanEmail: core.serialization.property("human_email", core.serialization.string()),
    instructions: core.serialization.string(),
});

export declare namespace AgentAttachHumanResponse {
    export interface Raw {
        human_email: string;
        instructions: string;
    }
}
