// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const AgentVerifyResponse: core.serialization.ObjectSchema<
    serializers.AgentVerifyResponse.Raw,
    AgentMail.AgentVerifyResponse
> = core.serialization.object({
    verified: core.serialization.boolean(),
});

export declare namespace AgentVerifyResponse {
    export interface Raw {
        verified: boolean;
    }
}
