// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const AgentSignupRequest: core.serialization.ObjectSchema<
    serializers.AgentSignupRequest.Raw,
    AgentMail.AgentSignupRequest
> = core.serialization.object({
    humanEmail: core.serialization.property("human_email", core.serialization.string()),
    username: core.serialization.string(),
});

export declare namespace AgentSignupRequest {
    export interface Raw {
        human_email: string;
        username: string;
    }
}
