// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const AgentVerifyRequest: core.serialization.ObjectSchema<
    serializers.AgentVerifyRequest.Raw,
    AgentMail.AgentVerifyRequest
> = core.serialization.object({
    otpCode: core.serialization.property("otp_code", core.serialization.string()),
});

export declare namespace AgentVerifyRequest {
    export interface Raw {
        otp_code: string;
    }
}
