/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../../../index.js";

export interface MessageReceived {
    type: "event";
    eventType: "message.received";
    eventId: AgentMail.EventId;
    message: AgentMail.Message;
}
