/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { InboxId } from "../../inboxes/types/InboxId.js";
import { MessageId } from "../../messages/types/MessageId.js";
import { Timestamp } from "./Timestamp.js";

export const Complaint: core.serialization.ObjectSchema<serializers.Complaint.Raw, AgentMail.Complaint> =
    core.serialization.object({
        inboxId: core.serialization.property("inbox_id", InboxId),
        messageId: core.serialization.property("message_id", MessageId),
        timestamp: Timestamp,
        type: core.serialization.string(),
        subType: core.serialization.property("sub_type", core.serialization.string()),
        recipients: core.serialization.list(core.serialization.string()),
    });

export declare namespace Complaint {
    export interface Raw {
        inbox_id: InboxId.Raw;
        message_id: MessageId.Raw;
        timestamp: Timestamp.Raw;
        type: string;
        sub_type: string;
        recipients: string[];
    }
}
