// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { InboxId } from "../../inboxes/types/InboxId.js";
import { MessageId } from "../../messages/types/MessageId.js";
import { Timestamp } from "./Timestamp.js";

export const Delivery: core.serialization.ObjectSchema<serializers.Delivery.Raw, AgentMail.Delivery> =
    core.serialization.object({
        inboxId: core.serialization.property("inbox_id", InboxId),
        messageId: core.serialization.property("message_id", MessageId),
        timestamp: Timestamp,
        recipients: core.serialization.list(core.serialization.string()),
    });

export declare namespace Delivery {
    export interface Raw {
        inbox_id: InboxId.Raw;
        message_id: MessageId.Raw;
        timestamp: Timestamp.Raw;
        recipients: string[];
    }
}
