// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const MessageReceivedEventType: core.serialization.Schema<
    serializers.MessageReceivedEventType.Raw,
    AgentMail.MessageReceivedEventType
> = core.serialization.enum_([
    "message.received",
    "message.received.spam",
    "message.received.blocked",
    "message.received.unauthenticated",
]);

export declare namespace MessageReceivedEventType {
    export type Raw =
        | "message.received"
        | "message.received.spam"
        | "message.received.blocked"
        | "message.received.unauthenticated";
}
