// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Message } from "../../messages/types/Message.js";
import { ThreadItem } from "../../threads/types/ThreadItem.js";
import { EventId } from "./EventId.js";

export const MessageReceivedSpamEvent: core.serialization.ObjectSchema<
    serializers.MessageReceivedSpamEvent.Raw,
    AgentMail.MessageReceivedSpamEvent
> = core.serialization.object({
    type: core.serialization.stringLiteral("event"),
    eventType: core.serialization.property("event_type", core.serialization.stringLiteral("message.received.spam")),
    eventId: core.serialization.property("event_id", EventId),
    message: Message,
    thread: ThreadItem,
});

export declare namespace MessageReceivedSpamEvent {
    export interface Raw {
        type: "event";
        event_type: "message.received.spam";
        event_id: EventId.Raw;
        message: Message.Raw;
        thread: ThreadItem.Raw;
    }
}
