/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { InboxId } from "../../inboxes/types/InboxId.js";
import { MessageId } from "../../messages/types/MessageId.js";
import { Timestamp } from "./Timestamp.js";

export const Reject: core.serialization.ObjectSchema<serializers.Reject.Raw, AgentMail.Reject> =
    core.serialization.object({
        inboxId: core.serialization.property("inbox_id", InboxId),
        messageId: core.serialization.property("message_id", MessageId),
        timestamp: Timestamp,
        reason: core.serialization.string(),
    });

export declare namespace Reject {
    export interface Raw {
        inbox_id: InboxId.Raw;
        message_id: MessageId.Raw;
        timestamp: Timestamp.Raw;
        reason: string;
    }
}
