// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const Timestamp: core.serialization.Schema<serializers.Timestamp.Raw, AgentMail.Timestamp> =
    core.serialization.date();

export declare namespace Timestamp {
    export type Raw = string;
}
