// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

export interface BatchUpdateMessagesResponse {
    limit: AgentMail.Limit;
    count: AgentMail.Count;
    /**
     * Updated messages with their new labels. Order matches `message_ids`
     * in the request. Excluded ids are omitted, so `count` may be less than
     * `limit`.
     */
    updates: AgentMail.UpdateMessageResponse[];
}
