/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../../../index";

export interface ListMessagesResponse {
    count: AgentMail.Count;
    limit?: AgentMail.Limit;
    lastKey?: AgentMail.LastKey;
    /** Message items. Ordered by `timestamp` descending. */
    messages: AgentMail.MessageItem[];
}
