/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../../../index";

export interface MessageItem {
    messageId: AgentMail.MessageId;
    threadId: AgentMail.ThreadId;
    sentAt: AgentMail.MessageSentAt;
    from: AgentMail.MessageFrom;
    subject?: AgentMail.MessageSubject;
    preview?: AgentMail.MessagePreview;
    to: AgentMail.MessageTo;
    cc?: AgentMail.MessageCc;
    bcc?: AgentMail.MessageBcc;
    attachments?: AgentMail.MessageAttachments;
}
