/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMailApi from "../../../index";

export interface MessageItem {
    messageId: AgentMailApi.MessageId;
    threadId: AgentMailApi.ThreadId;
    sentAt: AgentMailApi.MessageSentAt;
    from: AgentMailApi.MessageFrom;
    subject?: AgentMailApi.MessageSubject;
    preview?: AgentMailApi.MessagePreview;
    to: AgentMailApi.MessageTo;
    cc?: AgentMailApi.MessageCc;
    bcc?: AgentMailApi.MessageBcc;
    attachments?: AgentMailApi.MessageAttachments;
}
