/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../../../index";

export interface Message {
    inboxId: AgentMail.inboxes.InboxId;
    threadId: AgentMail.ThreadId;
    messageId: AgentMail.MessageId;
    eventId: AgentMail.MessageEventId;
    labels: AgentMail.MessageLabels;
    timestamp: AgentMail.MessageTimestamp;
    from: AgentMail.MessageFrom;
    to: AgentMail.MessageTo;
    cc?: AgentMail.MessageCc;
    bcc?: AgentMail.MessageBcc;
    subject?: AgentMail.MessageSubject;
    preview?: AgentMail.MessagePreview;
    text?: AgentMail.MessageText;
    html?: AgentMail.MessageHtml;
    attachments?: AgentMail.MessageAttachments;
    inReplyTo?: AgentMail.MessageInReplyTo;
    references?: AgentMail.MessageReferences;
}
