// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

/**
 * Attachments to include in message.
 */
export type SendMessageAttachments = AgentMail.SendAttachment[];
