/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../../../index";

export interface SendMessageRequest {
    to: AgentMail.SendMessageTo;
    cc?: AgentMail.SendMessageCc;
    bcc?: AgentMail.SendMessageBcc;
    subject?: AgentMail.MessageSubject;
    text?: AgentMail.MessageText;
    html?: AgentMail.MessageHtml;
    attachments?: AgentMail.SendMessageAttachments;
}
