/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMailApi from "../../../index";

/**
 * Recipient address or addresses.
 */
export type SendMessageTo = AgentMailApi.Addresses;
