/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentmailApi from "../../../index";

/**
 * Recipient address or addresses.
 */
export type SendMessageTo = AgentmailApi.Addresses;
