/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMailApi from "../../../index";

/**
 * CC recipient address or addresses.
 */
export type SendMessageCc = AgentMailApi.Addresses | undefined;
