/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMailApi from "../../../index";

export interface SendMessageRequest {
    to: AgentMailApi.SendMessageTo;
    cc?: AgentMailApi.SendMessageCc;
    bcc?: AgentMailApi.SendMessageBcc;
    subject?: AgentMailApi.MessageSubject;
    text?: AgentMailApi.MessageText;
    html?: AgentMailApi.MessageHtml;
}
