// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

export interface UpdateMessageRequest {
    /** Label or labels to add to message. */
    addLabels?: AgentMail.UpdateMessageLabels;
    /** Label or labels to remove from message. */
    removeLabels?: AgentMail.UpdateMessageLabels;
}
