// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GetInboxThreadRequest {
    /** Maximum number of messages to return. Cannot exceed 100. */
    limit?: AgentMail.Limit;
    /** Token returned by the previous response for retrieving the next, older page. */
    pageToken?: AgentMail.PageToken;
}
