/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../../../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListThreadsRequest {
    limit?: AgentMail.Limit;
    page_token?: AgentMail.PageToken;
    labels?: AgentMail.Labels;
    before?: AgentMail.Before;
    after?: AgentMail.After;
    ascending?: AgentMail.Ascending;
}
