// This file was auto-generated by Fern from our API Definition.

import * as AgentMail from "../../../src/api/index";
import { AgentMailClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("BrowserCredentialsClient", () => {
    test("createEnrollment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = { transaction_jti: "blackcurrant.........." };
        const rawResponseBody = {
            status: "pending",
            enrollment_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
            expires_at: 1,
        };

        server
            .mockEndpoint()
            .post("/v0/inboxes/inbox_id/browser-credentials/enrollments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.inboxes.browserCredentials.createEnrollment("inbox_id", {
            transactionJti: "blackcurrant..........",
        });
        expect(response).toEqual({
            status: "pending",
            enrollmentId: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
            expiresAt: 1,
        });
    });

    test("createEnrollment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = { transaction_jti: "blackcurrant.........." };
        const rawResponseBody = { name: "name", errors: { key: "value" } };

        server
            .mockEndpoint()
            .post("/v0/inboxes/inbox_id/browser-credentials/enrollments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.inboxes.browserCredentials.createEnrollment("inbox_id", {
                transactionJti: "blackcurrant..........",
            });
        }).rejects.toThrow(AgentMail.ValidationError);
    });

    test("createEnrollment (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = { transaction_jti: "blackcurrant.........." };
        const rawResponseBody = { name: "name", message: "message" };

        server
            .mockEndpoint()
            .post("/v0/inboxes/inbox_id/browser-credentials/enrollments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.inboxes.browserCredentials.createEnrollment("inbox_id", {
                transactionJti: "blackcurrant..........",
            });
        }).rejects.toThrow(AgentMail.NotFoundError);
    });

    test("createEnrollment (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = { transaction_jti: "blackcurrant.........." };
        const rawResponseBody = { name: "name", message: "message" };

        server
            .mockEndpoint()
            .post("/v0/inboxes/inbox_id/browser-credentials/enrollments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.inboxes.browserCredentials.createEnrollment("inbox_id", {
                transactionJti: "blackcurrant..........",
            });
        }).rejects.toThrow(AgentMail.ConflictError);
    });
});
