/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../mock-server/MockServerPool";
import { AgentMailClient } from "../../../src/Client";

describe("Drafts", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = {
            count: 1,
            limit: 1,
            next_page_token: "next_page_token",
            drafts: [
                {
                    inbox_id: "inbox_id",
                    thread_id: "thread_id",
                    draft_id: "draft_id",
                    labels: ["labels", "labels"],
                    to: ["to", "to"],
                    cc: ["cc", "cc"],
                    bcc: ["bcc", "bcc"],
                    subject: "subject",
                    preview: "preview",
                    attachments: [
                        {
                            attachment_id: "attachment_id",
                            filename: "filename",
                            content_type: "content_type",
                            size: 1,
                            inline: true,
                        },
                        {
                            attachment_id: "attachment_id",
                            filename: "filename",
                            content_type: "content_type",
                            size: 1,
                            inline: true,
                        },
                    ],
                    updated_at: "2024-01-15T09:30:00Z",
                },
                {
                    inbox_id: "inbox_id",
                    thread_id: "thread_id",
                    draft_id: "draft_id",
                    labels: ["labels", "labels"],
                    to: ["to", "to"],
                    cc: ["cc", "cc"],
                    bcc: ["bcc", "bcc"],
                    subject: "subject",
                    preview: "preview",
                    attachments: [
                        {
                            attachment_id: "attachment_id",
                            filename: "filename",
                            content_type: "content_type",
                            size: 1,
                            inline: true,
                        },
                        {
                            attachment_id: "attachment_id",
                            filename: "filename",
                            content_type: "content_type",
                            size: 1,
                            inline: true,
                        },
                    ],
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/v0/inboxes/inbox_id/drafts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.inboxes.drafts.list("inbox_id");
        expect(response).toEqual({
            count: 1,
            limit: 1,
            next_page_token: "next_page_token",
            drafts: [
                {
                    inbox_id: "inbox_id",
                    thread_id: "thread_id",
                    draft_id: "draft_id",
                    labels: ["labels", "labels"],
                    to: ["to", "to"],
                    cc: ["cc", "cc"],
                    bcc: ["bcc", "bcc"],
                    subject: "subject",
                    preview: "preview",
                    attachments: [
                        {
                            attachment_id: "attachment_id",
                            filename: "filename",
                            content_type: "content_type",
                            size: 1,
                            inline: true,
                        },
                        {
                            attachment_id: "attachment_id",
                            filename: "filename",
                            content_type: "content_type",
                            size: 1,
                            inline: true,
                        },
                    ],
                    updated_at: "2024-01-15T09:30:00Z",
                },
                {
                    inbox_id: "inbox_id",
                    thread_id: "thread_id",
                    draft_id: "draft_id",
                    labels: ["labels", "labels"],
                    to: ["to", "to"],
                    cc: ["cc", "cc"],
                    bcc: ["bcc", "bcc"],
                    subject: "subject",
                    preview: "preview",
                    attachments: [
                        {
                            attachment_id: "attachment_id",
                            filename: "filename",
                            content_type: "content_type",
                            size: 1,
                            inline: true,
                        },
                        {
                            attachment_id: "attachment_id",
                            filename: "filename",
                            content_type: "content_type",
                            size: 1,
                            inline: true,
                        },
                    ],
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = {
            inbox_id: "inbox_id",
            thread_id: "thread_id",
            draft_id: "draft_id",
            labels: ["labels", "labels"],
            reply_to: ["reply_to", "reply_to"],
            to: ["to", "to"],
            cc: ["cc", "cc"],
            bcc: ["bcc", "bcc"],
            subject: "subject",
            preview: "preview",
            text: "text",
            html: "html",
            attachments: [
                {
                    attachment_id: "attachment_id",
                    filename: "filename",
                    content_type: "content_type",
                    size: 1,
                    inline: true,
                },
                {
                    attachment_id: "attachment_id",
                    filename: "filename",
                    content_type: "content_type",
                    size: 1,
                    inline: true,
                },
            ],
            in_reply_to: "in_reply_to",
            references: ["references", "references"],
            updated_at: "2024-01-15T09:30:00Z",
            created_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .get("/v0/inboxes/inbox_id/drafts/draft_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.inboxes.drafts.get("inbox_id", "draft_id");
        expect(response).toEqual({
            inbox_id: "inbox_id",
            thread_id: "thread_id",
            draft_id: "draft_id",
            labels: ["labels", "labels"],
            reply_to: ["reply_to", "reply_to"],
            to: ["to", "to"],
            cc: ["cc", "cc"],
            bcc: ["bcc", "bcc"],
            subject: "subject",
            preview: "preview",
            text: "text",
            html: "html",
            attachments: [
                {
                    attachment_id: "attachment_id",
                    filename: "filename",
                    content_type: "content_type",
                    size: 1,
                    inline: true,
                },
                {
                    attachment_id: "attachment_id",
                    filename: "filename",
                    content_type: "content_type",
                    size: 1,
                    inline: true,
                },
            ],
            in_reply_to: "in_reply_to",
            references: ["references", "references"],
            updated_at: "2024-01-15T09:30:00Z",
            created_at: "2024-01-15T09:30:00Z",
        });
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = {
            labels: undefined,
            reply_to: undefined,
            to: undefined,
            cc: undefined,
            bcc: undefined,
            subject: undefined,
            text: undefined,
            html: undefined,
        };
        const rawResponseBody = {
            inbox_id: "inbox_id",
            thread_id: "thread_id",
            draft_id: "draft_id",
            labels: ["labels", "labels"],
            reply_to: ["reply_to", "reply_to"],
            to: ["to", "to"],
            cc: ["cc", "cc"],
            bcc: ["bcc", "bcc"],
            subject: "subject",
            preview: "preview",
            text: "text",
            html: "html",
            attachments: [
                {
                    attachment_id: "attachment_id",
                    filename: "filename",
                    content_type: "content_type",
                    size: 1,
                    inline: true,
                },
                {
                    attachment_id: "attachment_id",
                    filename: "filename",
                    content_type: "content_type",
                    size: 1,
                    inline: true,
                },
            ],
            in_reply_to: "in_reply_to",
            references: ["references", "references"],
            updated_at: "2024-01-15T09:30:00Z",
            created_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/v0/inboxes/inbox_id/drafts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.inboxes.drafts.create("inbox_id", {
            labels: undefined,
            reply_to: undefined,
            to: undefined,
            cc: undefined,
            bcc: undefined,
            subject: undefined,
            text: undefined,
            html: undefined,
        });
        expect(response).toEqual({
            inbox_id: "inbox_id",
            thread_id: "thread_id",
            draft_id: "draft_id",
            labels: ["labels", "labels"],
            reply_to: ["reply_to", "reply_to"],
            to: ["to", "to"],
            cc: ["cc", "cc"],
            bcc: ["bcc", "bcc"],
            subject: "subject",
            preview: "preview",
            text: "text",
            html: "html",
            attachments: [
                {
                    attachment_id: "attachment_id",
                    filename: "filename",
                    content_type: "content_type",
                    size: 1,
                    inline: true,
                },
                {
                    attachment_id: "attachment_id",
                    filename: "filename",
                    content_type: "content_type",
                    size: 1,
                    inline: true,
                },
            ],
            in_reply_to: "in_reply_to",
            references: ["references", "references"],
            updated_at: "2024-01-15T09:30:00Z",
            created_at: "2024-01-15T09:30:00Z",
        });
    });

    test("send", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = { add_labels: undefined, remove_labels: undefined };
        const rawResponseBody = { message_id: "message_id", thread_id: "thread_id" };
        server
            .mockEndpoint()
            .post("/v0/inboxes/inbox_id/drafts/draft_id/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.inboxes.drafts.send("inbox_id", "draft_id", {
            add_labels: undefined,
            remove_labels: undefined,
        });
        expect(response).toEqual({
            message_id: "message_id",
            thread_id: "thread_id",
        });
    });
});
