// This file was auto-generated by Fern from our API Definition.

import * as AgentMail from "../../../src/api/index";
import { AgentMailClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("DraftsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = {
            count: 1,
            limit: 1,
            next_page_token: "next_page_token",
            drafts: [
                {
                    inbox_id: "inbox_id",
                    thread_id: "thread_id",
                    draft_id: "draft_id",
                    labels: ["labels", "labels"],
                    to: ["to", "to"],
                    cc: ["cc", "cc"],
                    bcc: ["bcc", "bcc"],
                    subject: "subject",
                    preview: "preview",
                    attachments: [
                        {
                            attachment_id: "attachment_id",
                            filename: "filename",
                            size: 1,
                            content_type: "content_type",
                            content_disposition: "inline",
                            content_id: "content_id",
                        },
                        {
                            attachment_id: "attachment_id",
                            filename: "filename",
                            size: 1,
                            content_type: "content_type",
                            content_disposition: "inline",
                            content_id: "content_id",
                        },
                    ],
                    send_status: "scheduled",
                    send_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
                {
                    inbox_id: "inbox_id",
                    thread_id: "thread_id",
                    draft_id: "draft_id",
                    labels: ["labels", "labels"],
                    to: ["to", "to"],
                    cc: ["cc", "cc"],
                    bcc: ["bcc", "bcc"],
                    subject: "subject",
                    preview: "preview",
                    attachments: [
                        {
                            attachment_id: "attachment_id",
                            filename: "filename",
                            size: 1,
                            content_type: "content_type",
                            content_disposition: "inline",
                            content_id: "content_id",
                        },
                        {
                            attachment_id: "attachment_id",
                            filename: "filename",
                            size: 1,
                            content_type: "content_type",
                            content_disposition: "inline",
                            content_id: "content_id",
                        },
                    ],
                    send_status: "scheduled",
                    send_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/v0/inboxes/inbox_id/drafts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.inboxes.drafts.list("inbox_id");
        expect(response).toEqual({
            count: 1,
            limit: 1,
            nextPageToken: "next_page_token",
            drafts: [
                {
                    inboxId: "inbox_id",
                    threadId: "thread_id",
                    draftId: "draft_id",
                    labels: ["labels", "labels"],
                    to: ["to", "to"],
                    cc: ["cc", "cc"],
                    bcc: ["bcc", "bcc"],
                    subject: "subject",
                    preview: "preview",
                    attachments: [
                        {
                            attachmentId: "attachment_id",
                            filename: "filename",
                            size: 1,
                            contentType: "content_type",
                            contentDisposition: "inline",
                            contentId: "content_id",
                        },
                        {
                            attachmentId: "attachment_id",
                            filename: "filename",
                            size: 1,
                            contentType: "content_type",
                            contentDisposition: "inline",
                            contentId: "content_id",
                        },
                    ],
                    sendStatus: "scheduled",
                    sendAt: new Date("2024-01-15T09:30:00.000Z"),
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                },
                {
                    inboxId: "inbox_id",
                    threadId: "thread_id",
                    draftId: "draft_id",
                    labels: ["labels", "labels"],
                    to: ["to", "to"],
                    cc: ["cc", "cc"],
                    bcc: ["bcc", "bcc"],
                    subject: "subject",
                    preview: "preview",
                    attachments: [
                        {
                            attachmentId: "attachment_id",
                            filename: "filename",
                            size: 1,
                            contentType: "content_type",
                            contentDisposition: "inline",
                            contentId: "content_id",
                        },
                        {
                            attachmentId: "attachment_id",
                            filename: "filename",
                            size: 1,
                            contentType: "content_type",
                            contentDisposition: "inline",
                            contentId: "content_id",
                        },
                    ],
                    sendStatus: "scheduled",
                    sendAt: new Date("2024-01-15T09:30:00.000Z"),
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                },
            ],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = { name: "name", message: "message" };
        server
            .mockEndpoint()
            .get("/v0/inboxes/inbox_id/drafts")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.inboxes.drafts.list("inbox_id");
        }).rejects.toThrow(AgentMail.NotFoundError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = {
            inbox_id: "inbox_id",
            thread_id: "thread_id",
            draft_id: "draft_id",
            client_id: "client_id",
            labels: ["labels", "labels"],
            reply_to: ["reply_to", "reply_to"],
            to: ["to", "to"],
            cc: ["cc", "cc"],
            bcc: ["bcc", "bcc"],
            subject: "subject",
            preview: "preview",
            text: "text",
            html: "html",
            attachments: [
                {
                    attachment_id: "attachment_id",
                    filename: "filename",
                    size: 1,
                    content_type: "content_type",
                    content_disposition: "inline",
                    content_id: "content_id",
                },
                {
                    attachment_id: "attachment_id",
                    filename: "filename",
                    size: 1,
                    content_type: "content_type",
                    content_disposition: "inline",
                    content_id: "content_id",
                },
            ],
            in_reply_to: "in_reply_to",
            references: ["references", "references"],
            send_status: "scheduled",
            send_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .get("/v0/inboxes/inbox_id/drafts/draft_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.inboxes.drafts.get("inbox_id", "draft_id");
        expect(response).toEqual({
            inboxId: "inbox_id",
            threadId: "thread_id",
            draftId: "draft_id",
            clientId: "client_id",
            labels: ["labels", "labels"],
            replyTo: ["reply_to", "reply_to"],
            to: ["to", "to"],
            cc: ["cc", "cc"],
            bcc: ["bcc", "bcc"],
            subject: "subject",
            preview: "preview",
            text: "text",
            html: "html",
            attachments: [
                {
                    attachmentId: "attachment_id",
                    filename: "filename",
                    size: 1,
                    contentType: "content_type",
                    contentDisposition: "inline",
                    contentId: "content_id",
                },
                {
                    attachmentId: "attachment_id",
                    filename: "filename",
                    size: 1,
                    contentType: "content_type",
                    contentDisposition: "inline",
                    contentId: "content_id",
                },
            ],
            inReplyTo: "in_reply_to",
            references: ["references", "references"],
            sendStatus: "scheduled",
            sendAt: new Date("2024-01-15T09:30:00.000Z"),
            updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            createdAt: new Date("2024-01-15T09:30:00.000Z"),
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = { name: "name", message: "message" };
        server
            .mockEndpoint()
            .get("/v0/inboxes/inbox_id/drafts/draft_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.inboxes.drafts.get("inbox_id", "draft_id");
        }).rejects.toThrow(AgentMail.NotFoundError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            inbox_id: "inbox_id",
            thread_id: "thread_id",
            draft_id: "draft_id",
            client_id: "client_id",
            labels: ["labels", "labels"],
            reply_to: ["reply_to", "reply_to"],
            to: ["to", "to"],
            cc: ["cc", "cc"],
            bcc: ["bcc", "bcc"],
            subject: "subject",
            preview: "preview",
            text: "text",
            html: "html",
            attachments: [
                {
                    attachment_id: "attachment_id",
                    filename: "filename",
                    size: 1,
                    content_type: "content_type",
                    content_disposition: "inline",
                    content_id: "content_id",
                },
                {
                    attachment_id: "attachment_id",
                    filename: "filename",
                    size: 1,
                    content_type: "content_type",
                    content_disposition: "inline",
                    content_id: "content_id",
                },
            ],
            in_reply_to: "in_reply_to",
            references: ["references", "references"],
            send_status: "scheduled",
            send_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/v0/inboxes/inbox_id/drafts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.inboxes.drafts.create("inbox_id", {});
        expect(response).toEqual({
            inboxId: "inbox_id",
            threadId: "thread_id",
            draftId: "draft_id",
            clientId: "client_id",
            labels: ["labels", "labels"],
            replyTo: ["reply_to", "reply_to"],
            to: ["to", "to"],
            cc: ["cc", "cc"],
            bcc: ["bcc", "bcc"],
            subject: "subject",
            preview: "preview",
            text: "text",
            html: "html",
            attachments: [
                {
                    attachmentId: "attachment_id",
                    filename: "filename",
                    size: 1,
                    contentType: "content_type",
                    contentDisposition: "inline",
                    contentId: "content_id",
                },
                {
                    attachmentId: "attachment_id",
                    filename: "filename",
                    size: 1,
                    contentType: "content_type",
                    contentDisposition: "inline",
                    contentId: "content_id",
                },
            ],
            inReplyTo: "in_reply_to",
            references: ["references", "references"],
            sendStatus: "scheduled",
            sendAt: new Date("2024-01-15T09:30:00.000Z"),
            updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            createdAt: new Date("2024-01-15T09:30:00.000Z"),
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { name: "name", message: "message" };
        server
            .mockEndpoint()
            .post("/v0/inboxes/inbox_id/drafts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.inboxes.drafts.create("inbox_id", {});
        }).rejects.toThrow(AgentMail.NotFoundError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            inbox_id: "inbox_id",
            thread_id: "thread_id",
            draft_id: "draft_id",
            client_id: "client_id",
            labels: ["labels", "labels"],
            reply_to: ["reply_to", "reply_to"],
            to: ["to", "to"],
            cc: ["cc", "cc"],
            bcc: ["bcc", "bcc"],
            subject: "subject",
            preview: "preview",
            text: "text",
            html: "html",
            attachments: [
                {
                    attachment_id: "attachment_id",
                    filename: "filename",
                    size: 1,
                    content_type: "content_type",
                    content_disposition: "inline",
                    content_id: "content_id",
                },
                {
                    attachment_id: "attachment_id",
                    filename: "filename",
                    size: 1,
                    content_type: "content_type",
                    content_disposition: "inline",
                    content_id: "content_id",
                },
            ],
            in_reply_to: "in_reply_to",
            references: ["references", "references"],
            send_status: "scheduled",
            send_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .patch("/v0/inboxes/inbox_id/drafts/draft_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.inboxes.drafts.update("inbox_id", "draft_id", {});
        expect(response).toEqual({
            inboxId: "inbox_id",
            threadId: "thread_id",
            draftId: "draft_id",
            clientId: "client_id",
            labels: ["labels", "labels"],
            replyTo: ["reply_to", "reply_to"],
            to: ["to", "to"],
            cc: ["cc", "cc"],
            bcc: ["bcc", "bcc"],
            subject: "subject",
            preview: "preview",
            text: "text",
            html: "html",
            attachments: [
                {
                    attachmentId: "attachment_id",
                    filename: "filename",
                    size: 1,
                    contentType: "content_type",
                    contentDisposition: "inline",
                    contentId: "content_id",
                },
                {
                    attachmentId: "attachment_id",
                    filename: "filename",
                    size: 1,
                    contentType: "content_type",
                    contentDisposition: "inline",
                    contentId: "content_id",
                },
            ],
            inReplyTo: "in_reply_to",
            references: ["references", "references"],
            sendStatus: "scheduled",
            sendAt: new Date("2024-01-15T09:30:00.000Z"),
            updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            createdAt: new Date("2024-01-15T09:30:00.000Z"),
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { name: "name", message: "message" };
        server
            .mockEndpoint()
            .patch("/v0/inboxes/inbox_id/drafts/draft_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.inboxes.drafts.update("inbox_id", "draft_id", {});
        }).rejects.toThrow(AgentMail.NotFoundError);
    });

    test("send (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { message_id: "message_id", thread_id: "thread_id" };
        server
            .mockEndpoint()
            .post("/v0/inboxes/inbox_id/drafts/draft_id/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.inboxes.drafts.send("inbox_id", "draft_id", {});
        expect(response).toEqual({
            messageId: "message_id",
            threadId: "thread_id",
        });
    });

    test("send (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { name: "name", message: "message" };
        server
            .mockEndpoint()
            .post("/v0/inboxes/inbox_id/drafts/draft_id/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.inboxes.drafts.send("inbox_id", "draft_id", {});
        }).rejects.toThrow(AgentMail.NotFoundError);
    });

    test("send (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { name: "name", errors: { key: "value" } };
        server
            .mockEndpoint()
            .post("/v0/inboxes/inbox_id/drafts/draft_id/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.inboxes.drafts.send("inbox_id", "draft_id", {});
        }).rejects.toThrow(AgentMail.ValidationError);
    });

    test("send (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { name: "name", message: "message" };
        server
            .mockEndpoint()
            .post("/v0/inboxes/inbox_id/drafts/draft_id/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.inboxes.drafts.send("inbox_id", "draft_id", {});
        }).rejects.toThrow(AgentMail.MessageRejectedError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        server.mockEndpoint().delete("/v0/inboxes/inbox_id/drafts/draft_id").respondWith().statusCode(200).build();

        const response = await client.inboxes.drafts.delete("inbox_id", "draft_id");
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = { name: "name", message: "message" };
        server
            .mockEndpoint()
            .delete("/v0/inboxes/inbox_id/drafts/draft_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.inboxes.drafts.delete("inbox_id", "draft_id");
        }).rejects.toThrow(AgentMail.NotFoundError);
    });
});
