// This file was auto-generated by Fern from our API Definition.

import * as AgentMail from "../../../src/api/index";
import { AgentMailClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("InboxesClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = {
            count: 1,
            limit: 1,
            next_page_token: "next_page_token",
            inboxes: [
                {
                    pod_id: "pod_id",
                    inbox_id: "inbox_id",
                    email: "email",
                    display_name: "display_name",
                    client_id: "client_id",
                    metadata: { metadata: "metadata" },
                    updated_at: "2024-01-15T09:30:00Z",
                    created_at: "2024-01-15T09:30:00Z",
                },
                {
                    pod_id: "pod_id",
                    inbox_id: "inbox_id",
                    email: "email",
                    display_name: "display_name",
                    client_id: "client_id",
                    metadata: { metadata: "metadata" },
                    updated_at: "2024-01-15T09:30:00Z",
                    created_at: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server.mockEndpoint().get("/v0/inboxes").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.inboxes.list();
        expect(response).toEqual({
            count: 1,
            limit: 1,
            nextPageToken: "next_page_token",
            inboxes: [
                {
                    podId: "pod_id",
                    inboxId: "inbox_id",
                    email: "email",
                    displayName: "display_name",
                    clientId: "client_id",
                    metadata: {
                        metadata: "metadata",
                    },
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                    createdAt: new Date("2024-01-15T09:30:00.000Z"),
                },
                {
                    podId: "pod_id",
                    inboxId: "inbox_id",
                    email: "email",
                    displayName: "display_name",
                    clientId: "client_id",
                    metadata: {
                        metadata: "metadata",
                    },
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                    createdAt: new Date("2024-01-15T09:30:00.000Z"),
                },
            ],
        });
    });

    test("search (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = {
            count: 1,
            limit: 1,
            next_page_token: "next_page_token",
            inboxes: [
                {
                    pod_id: "pod_id",
                    inbox_id: "inbox_id",
                    email: "email",
                    display_name: "display_name",
                    client_id: "client_id",
                    metadata: { metadata: "metadata" },
                    updated_at: "2024-01-15T09:30:00Z",
                    created_at: "2024-01-15T09:30:00Z",
                },
                {
                    pod_id: "pod_id",
                    inbox_id: "inbox_id",
                    email: "email",
                    display_name: "display_name",
                    client_id: "client_id",
                    metadata: { metadata: "metadata" },
                    updated_at: "2024-01-15T09:30:00Z",
                    created_at: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server.mockEndpoint().get("/v0/inboxes/search").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.inboxes.search({
            q: "q",
        });
        expect(response).toEqual({
            count: 1,
            limit: 1,
            nextPageToken: "next_page_token",
            inboxes: [
                {
                    podId: "pod_id",
                    inboxId: "inbox_id",
                    email: "email",
                    displayName: "display_name",
                    clientId: "client_id",
                    metadata: {
                        metadata: "metadata",
                    },
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                    createdAt: new Date("2024-01-15T09:30:00.000Z"),
                },
                {
                    podId: "pod_id",
                    inboxId: "inbox_id",
                    email: "email",
                    displayName: "display_name",
                    clientId: "client_id",
                    metadata: {
                        metadata: "metadata",
                    },
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                    createdAt: new Date("2024-01-15T09:30:00.000Z"),
                },
            ],
        });
    });

    test("search (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = { name: "name", errors: { key: "value" } };

        server.mockEndpoint().get("/v0/inboxes/search").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.inboxes.search({
                q: "q",
            });
        }).rejects.toThrow(AgentMail.ValidationError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = {
            pod_id: "pod_id",
            inbox_id: "inbox_id",
            email: "email",
            display_name: "display_name",
            client_id: "client_id",
            metadata: { metadata: "metadata" },
            updated_at: "2024-01-15T09:30:00Z",
            created_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/v0/inboxes/inbox_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.inboxes.get("inbox_id");
        expect(response).toEqual({
            podId: "pod_id",
            inboxId: "inbox_id",
            email: "email",
            displayName: "display_name",
            clientId: "client_id",
            metadata: {
                metadata: "metadata",
            },
            updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            createdAt: new Date("2024-01-15T09:30:00.000Z"),
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = { name: "name", message: "message" };

        server
            .mockEndpoint()
            .get("/v0/inboxes/inbox_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.inboxes.get("inbox_id");
        }).rejects.toThrow(AgentMail.NotFoundError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = {
            pod_id: "pod_id",
            inbox_id: "inbox_id",
            email: "email",
            display_name: "display_name",
            client_id: "client_id",
            metadata: { metadata: "metadata" },
            updated_at: "2024-01-15T09:30:00Z",
            created_at: "2024-01-15T09:30:00Z",
        };

        server.mockEndpoint().post("/v0/inboxes").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.inboxes.create(undefined);
        expect(response).toEqual({
            podId: "pod_id",
            inboxId: "inbox_id",
            email: "email",
            displayName: "display_name",
            clientId: "client_id",
            metadata: {
                metadata: "metadata",
            },
            updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            createdAt: new Date("2024-01-15T09:30:00.000Z"),
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = { name: "name", errors: { key: "value" } };

        server.mockEndpoint().post("/v0/inboxes").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.inboxes.create(undefined);
        }).rejects.toThrow(AgentMail.ValidationError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = { name: "name", message: "message" };

        server.mockEndpoint().post("/v0/inboxes").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.inboxes.create(undefined);
        }).rejects.toThrow(AgentMail.UnprocessableError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            pod_id: "pod_id",
            inbox_id: "inbox_id",
            email: "email",
            display_name: "display_name",
            client_id: "client_id",
            metadata: { metadata: "metadata" },
            updated_at: "2024-01-15T09:30:00Z",
            created_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .patch("/v0/inboxes/inbox_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.inboxes.update("inbox_id", {});
        expect(response).toEqual({
            podId: "pod_id",
            inboxId: "inbox_id",
            email: "email",
            displayName: "display_name",
            clientId: "client_id",
            metadata: {
                metadata: "metadata",
            },
            updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            createdAt: new Date("2024-01-15T09:30:00.000Z"),
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { name: "name", message: "message" };

        server
            .mockEndpoint()
            .patch("/v0/inboxes/inbox_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.inboxes.update("inbox_id", {});
        }).rejects.toThrow(AgentMail.NotFoundError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { name: "name", errors: { key: "value" } };

        server
            .mockEndpoint()
            .patch("/v0/inboxes/inbox_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.inboxes.update("inbox_id", {});
        }).rejects.toThrow(AgentMail.ValidationError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        server.mockEndpoint().delete("/v0/inboxes/inbox_id").respondWith().statusCode(200).build();

        const response = await client.inboxes.delete("inbox_id");
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = { name: "name", message: "message" };

        server
            .mockEndpoint()
            .delete("/v0/inboxes/inbox_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.inboxes.delete("inbox_id");
        }).rejects.toThrow(AgentMail.NotFoundError);
    });

    test("authorize (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = { auth_token: "blackcurrant.........." };
        const rawResponseBody = {
            type: "public_key",
            api_key_id: "api_key_id",
            client_id: "client_id",
            name: "name",
            public_key: {
                jwk: {
                    kty: "EC",
                    crv: "P-256",
                    x: "blackcurrant...............................",
                    y: "blackcurrant...............................",
                },
                fingerprint: "blackcurrant...............................",
            },
            pod_id: "pod_id",
            inbox_id: "inbox_id",
            status: "pending",
            used_at: "2024-01-15T09:30:00Z",
            permissions: {
                inbox_read: true,
                inbox_create: true,
                inbox_update: true,
                inbox_delete: true,
                message_read: true,
                message_send: true,
                message_update: true,
                message_delete: true,
                label_spam_read: true,
                label_blocked_read: true,
                label_unauthenticated_read: true,
                label_trash_read: true,
                draft_read: true,
                draft_create: true,
                draft_update: true,
                draft_delete: true,
                draft_send: true,
                webhook_read: true,
                webhook_create: true,
                webhook_update: true,
                webhook_delete: true,
                domain_read: true,
                domain_create: true,
                domain_update: true,
                domain_delete: true,
                list_entry_read: true,
                list_entry_create: true,
                list_entry_delete: true,
                metrics_read: true,
                api_key_read: true,
                api_key_create: true,
                api_key_update: true,
                api_key_delete: true,
                provider_connect: true,
                provider_share_owner: true,
                pod_read: true,
                pod_create: true,
                pod_delete: true,
            },
            created_by: { api_key_id: "api_key_id" },
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            expires_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/v0/inboxes/inbox_id/authorize")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.inboxes.authorize("inbox_id", {
            authToken: "blackcurrant..........",
        });
        expect(response).toEqual({
            type: "public_key",
            apiKeyId: "api_key_id",
            clientId: "client_id",
            name: "name",
            publicKey: {
                jwk: {
                    kty: "EC",
                    crv: "P-256",
                    x: "blackcurrant...............................",
                    y: "blackcurrant...............................",
                },
                fingerprint: "blackcurrant...............................",
            },
            podId: "pod_id",
            inboxId: "inbox_id",
            status: "pending",
            usedAt: new Date("2024-01-15T09:30:00.000Z"),
            permissions: {
                inboxRead: true,
                inboxCreate: true,
                inboxUpdate: true,
                inboxDelete: true,
                messageRead: true,
                messageSend: true,
                messageUpdate: true,
                messageDelete: true,
                labelSpamRead: true,
                labelBlockedRead: true,
                labelUnauthenticatedRead: true,
                labelTrashRead: true,
                draftRead: true,
                draftCreate: true,
                draftUpdate: true,
                draftDelete: true,
                draftSend: true,
                webhookRead: true,
                webhookCreate: true,
                webhookUpdate: true,
                webhookDelete: true,
                domainRead: true,
                domainCreate: true,
                domainUpdate: true,
                domainDelete: true,
                listEntryRead: true,
                listEntryCreate: true,
                listEntryDelete: true,
                metricsRead: true,
                apiKeyRead: true,
                apiKeyCreate: true,
                apiKeyUpdate: true,
                apiKeyDelete: true,
                providerConnect: true,
                providerShareOwner: true,
                podRead: true,
                podCreate: true,
                podDelete: true,
            },
            createdBy: {
                apiKeyId: "api_key_id",
            },
            createdAt: new Date("2024-01-15T09:30:00.000Z"),
            updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            expiresAt: new Date("2024-01-15T09:30:00.000Z"),
        });
    });

    test("authorize (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = { auth_token: "blackcurrant.........." };
        const rawResponseBody = { name: "name", errors: { key: "value" } };

        server
            .mockEndpoint()
            .post("/v0/inboxes/inbox_id/authorize")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.inboxes.authorize("inbox_id", {
                authToken: "blackcurrant..........",
            });
        }).rejects.toThrow(AgentMail.ValidationError);
    });

    test("authorize (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });
        const rawRequestBody = { auth_token: "blackcurrant.........." };
        const rawResponseBody = { name: "name", message: "message" };

        server
            .mockEndpoint()
            .post("/v0/inboxes/inbox_id/authorize")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.inboxes.authorize("inbox_id", {
                authToken: "blackcurrant..........",
            });
        }).rejects.toThrow(AgentMail.NotFoundError);
    });
});
