// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

export interface Attachment {
    attachmentId: AgentMail.AttachmentId;
    filename?: AgentMail.AttachmentFilename;
    contentType?: AgentMail.AttachmentContentType;
    size: AgentMail.AttachmentSize;
    inline: AgentMail.AttachmentInline;
}
