/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../../../index";

export interface CreateContextRequest {
    type: AgentMail.ContextType;
    data: AgentMail.ContextData;
    metadata?: AgentMail.ContextMetadata;
    isEvent: AgentMail.ContextIsEvent;
}
