// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const CalendarEventSource: core.serialization.Schema<
    serializers.CalendarEventSource.Raw,
    AgentMail.CalendarEventSource
> = core.serialization.enum_(["api", "email"]);

export declare namespace CalendarEventSource {
    export type Raw = "api" | "email";
}
