// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const IncludeOverlapping: core.serialization.Schema<
    serializers.IncludeOverlapping.Raw,
    AgentMail.IncludeOverlapping
> = core.serialization.boolean();

export declare namespace IncludeOverlapping {
    export type Raw = boolean;
}
