// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const InstanceMutationMode: core.serialization.Schema<
    serializers.InstanceMutationMode.Raw,
    AgentMail.InstanceMutationMode
> = core.serialization.enum_(["single", "future"]);

export declare namespace InstanceMutationMode {
    export type Raw = "single" | "future";
}
