// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { IanaTimezone } from "./IanaTimezone.js";

export const UpdateCalendarRequest: core.serialization.ObjectSchema<
    serializers.UpdateCalendarRequest.Raw,
    AgentMail.UpdateCalendarRequest
> = core.serialization.object({
    timezone: IanaTimezone,
});

export declare namespace UpdateCalendarRequest {
    export interface Raw {
        timezone: IanaTimezone.Raw;
    }
}
