// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Count } from "../../../types/Count.js";
import { Limit } from "../../../types/Limit.js";
import { UpdateMessageResponse } from "./UpdateMessageResponse.js";

export const BatchUpdateMessagesResponse: core.serialization.ObjectSchema<
    serializers.BatchUpdateMessagesResponse.Raw,
    AgentMail.BatchUpdateMessagesResponse
> = core.serialization.object({
    limit: Limit,
    count: Count,
    updates: core.serialization.list(UpdateMessageResponse),
});

export declare namespace BatchUpdateMessagesResponse {
    export interface Raw {
        limit: Limit.Raw;
        count: Count.Raw;
        updates: UpdateMessageResponse.Raw[];
    }
}
