// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Count } from "../../../types/Count.js";
import { Limit } from "../../../types/Limit.js";
import { Message } from "./Message.js";

export const BatchGetMessagesResponse: core.serialization.ObjectSchema<
    serializers.BatchGetMessagesResponse.Raw,
    AgentMail.BatchGetMessagesResponse
> = core.serialization.object({
    limit: Limit,
    count: Count,
    messages: core.serialization.list(Message),
});

export declare namespace BatchGetMessagesResponse {
    export interface Raw {
        limit: Limit.Raw;
        count: Count.Raw;
        messages: Message.Raw[];
    }
}
