/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const MessageFrom: core.serialization.Schema<serializers.MessageFrom.Raw, AgentMail.MessageFrom> =
    core.serialization.string();

export declare namespace MessageFrom {
    export type Raw = string;
}
