/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { InboxId } from "../../inboxes/types/InboxId.js";
import { ThreadId } from "../../threads/types/ThreadId.js";
import { MessageId } from "./MessageId.js";
import { MessageLabels } from "./MessageLabels.js";
import { MessageTimestamp } from "./MessageTimestamp.js";
import { MessageFrom } from "./MessageFrom.js";
import { MessageTo } from "./MessageTo.js";
import { MessageCc } from "./MessageCc.js";
import { MessageBcc } from "./MessageBcc.js";
import { MessageSubject } from "./MessageSubject.js";
import { MessagePreview } from "./MessagePreview.js";
import { MessageText } from "./MessageText.js";
import { MessageHtml } from "./MessageHtml.js";
import { MessageAttachments } from "./MessageAttachments.js";
import { Attachment } from "../../attachments/types/Attachment.js";

export const Message: core.serialization.ObjectSchema<serializers.Message.Raw, AgentMail.Message> =
    core.serialization.object({
        inboxId: core.serialization.property("inbox_id", InboxId),
        threadId: core.serialization.property("thread_id", ThreadId),
        messageId: core.serialization.property("message_id", MessageId),
        labels: MessageLabels,
        timestamp: MessageTimestamp,
        from: MessageFrom,
        replyTo: core.serialization.property(
            "reply_to",
            core.serialization.list(core.serialization.string()).optional(),
        ),
        to: MessageTo,
        cc: MessageCc.optional(),
        bcc: MessageBcc.optional(),
        subject: MessageSubject.optional(),
        preview: MessagePreview.optional(),
        text: MessageText.optional(),
        html: MessageHtml.optional(),
        attachments: MessageAttachments.optional(),
        inReplyTo: core.serialization.property("in_reply_to", core.serialization.string().optional()),
        references: core.serialization.list(core.serialization.string()).optional(),
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
    });

export declare namespace Message {
    export interface Raw {
        inbox_id: InboxId.Raw;
        thread_id: ThreadId.Raw;
        message_id: MessageId.Raw;
        labels: MessageLabels.Raw;
        timestamp: MessageTimestamp.Raw;
        from: MessageFrom.Raw;
        reply_to?: string[] | null;
        to: MessageTo.Raw;
        cc?: MessageCc.Raw | null;
        bcc?: MessageBcc.Raw | null;
        subject?: MessageSubject.Raw | null;
        preview?: MessagePreview.Raw | null;
        text?: MessageText.Raw | null;
        html?: MessageHtml.Raw | null;
        attachments?: MessageAttachments.Raw | null;
        in_reply_to?: string | null;
        references?: string[] | null;
        updated_at: string;
        created_at: string;
    }
}
