/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as AgentmailApi from "../../../../api/index";
import * as core from "../../../../core";

export const MessageSubject: core.serialization.Schema<serializers.MessageSubject.Raw, AgentmailApi.MessageSubject> =
    core.serialization.string().optional();

export declare namespace MessageSubject {
    export type Raw = string | null | undefined;
}
