/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as AgentmailApi from "../../../../api/index";
import * as core from "../../../../core";

export const MessageCc: core.serialization.Schema<serializers.MessageCc.Raw, AgentmailApi.MessageCc> =
    core.serialization.list(core.serialization.string()).optional();

export declare namespace MessageCc {
    export type Raw = string[] | null | undefined;
}
