// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const SendMessageHeaders: core.serialization.Schema<
    serializers.SendMessageHeaders.Raw,
    AgentMail.SendMessageHeaders
> = core.serialization.record(core.serialization.string(), core.serialization.string());

export declare namespace SendMessageHeaders {
    export type Raw = Record<string, string>;
}
