/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
import { Addresses } from "./Addresses";

export const SendMessageTo: core.serialization.Schema<serializers.SendMessageTo.Raw, AgentMail.SendMessageTo> =
    Addresses;

export declare namespace SendMessageTo {
    export type Raw = Addresses.Raw;
}
