/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as AgentmailApi from "../../../../api/index";
import * as core from "../../../../core";
import { Addresses } from "./Addresses";

export const SendMessageBcc: core.serialization.Schema<serializers.SendMessageBcc.Raw, AgentmailApi.SendMessageBcc> =
    Addresses.optional();

export declare namespace SendMessageBcc {
    export type Raw = Addresses.Raw | null | undefined;
}
