/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
import { Addresses } from "./Addresses";

export const SendMessageReplyTo: core.serialization.Schema<
    serializers.SendMessageReplyTo.Raw,
    AgentMail.SendMessageReplyTo
> = Addresses;

export declare namespace SendMessageReplyTo {
    export type Raw = Addresses.Raw;
}
