// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const UpdateMessageLabels: core.serialization.Schema<
    serializers.UpdateMessageLabels.Raw,
    AgentMail.UpdateMessageLabels
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace UpdateMessageLabels {
    export type Raw = string | string[];
}
