// This file was auto-generated by Fern from our API Definition.

export const EventType = {
    MessageReceived: "message.received",
    MessageSent: "message.sent",
    MessageDelivered: "message.delivered",
    MessageBounced: "message.bounced",
    MessageComplained: "message.complained",
    MessageRejected: "message.rejected",
} as const;
export type EventType = (typeof EventType)[keyof typeof EventType];
