/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../../../index";

export interface MessageReceivedPayload extends AgentMail.Payload {
    message: AgentMail.Message;
}
