// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

export interface UpdateWebhookRequest extends AgentMail.webhooks.UpdatePodWebhookRequest {
    /** Pod IDs to subscribe to the webhook. */
    addPodIds?: AgentMail.PodIds;
    /** Pod IDs to unsubscribe from the webhook. */
    removePodIds?: AgentMail.PodIds;
}
