/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../../../index";

export interface Webhook {
    webhookId: AgentMail.WebhookId;
    url: AgentMail.Url;
    events?: AgentMail.Events;
    inboxes?: AgentMail.Inboxes;
    /** Secret for webhook signature verification. */
    secret: string;
    /** Time at which webhook was created. */
    createdAt: Date;
}
