// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ClientId } from "./ClientId.js";
import { DisplayName } from "./DisplayName.js";

export const CreateInboxRequest: core.serialization.ObjectSchema<
    serializers.inboxes.CreateInboxRequest.Raw,
    AgentMail.inboxes.CreateInboxRequest
> = core.serialization.object({
    username: core.serialization.string().optional(),
    domain: core.serialization.string().optional(),
    displayName: core.serialization.property("display_name", DisplayName.optional()),
    clientId: core.serialization.property("client_id", ClientId.optional()),
});

export declare namespace CreateInboxRequest {
    export interface Raw {
        username?: string | null;
        domain?: string | null;
        display_name?: DisplayName.Raw | null;
        client_id?: ClientId.Raw | null;
    }
}
