// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Count } from "../../../types/Count.js";
import { Limit } from "../../../types/Limit.js";
import { PageToken } from "../../../types/PageToken.js";
import { Inbox } from "./Inbox.js";

export const ListInboxesResponse: core.serialization.ObjectSchema<
    serializers.inboxes.ListInboxesResponse.Raw,
    AgentMail.inboxes.ListInboxesResponse
> = core.serialization.object({
    count: Count,
    limit: Limit.optional(),
    nextPageToken: core.serialization.property("next_page_token", PageToken.optional()),
    inboxes: core.serialization.list(Inbox),
});

export declare namespace ListInboxesResponse {
    export interface Raw {
        count: Count.Raw;
        limit?: Limit.Raw | null;
        next_page_token?: PageToken.Raw | null;
        inboxes: Inbox.Raw[];
    }
}
