/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
import { Inbox } from "./Inbox";
import { Limit } from "../../../types/Limit";
import { Count } from "../../../types/Count";
import { LastKey } from "../../../types/LastKey";

export const ListInboxesResponse: core.serialization.ObjectSchema<
    serializers.ListInboxesResponse.Raw,
    AgentMail.ListInboxesResponse
> = core.serialization.object({
    inboxes: core.serialization.list(Inbox),
    limit: Limit,
    count: Count,
    lastKey: core.serialization.property("last_key", LastKey),
});

export declare namespace ListInboxesResponse {
    export interface Raw {
        inboxes: Inbox.Raw[];
        limit: Limit.Raw;
        count: Count.Raw;
        last_key?: LastKey.Raw;
    }
}
