// This file was auto-generated by Fern from our API Definition.

/**
 * Accept the app's disclosure on the agent's behalf, skipping the
 * first-use disclosure page. Requires `app_share_owner` when owner
 * scopes are involved.
 */
export type AcceptDisclosure = boolean;
