// This file was auto-generated by Fern from our API Definition.

export const ApiKeyType = {
    Bearer: "bearer",
    PublicKey: "public_key",
} as const;
export type ApiKeyType = (typeof ApiKeyType)[keyof typeof ApiKeyType];
