// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

/**
 * The bearer API key that created the credential. Provenance only; the credential outlives it.
 */
export interface ApiKeyCreator {
    apiKeyId: AgentMail.ApiKeyId;
}
