// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

export interface BrowserEnrollmentLifecycleEvent {
    type: AgentMail.BrowserEnrollmentLifecycleEventType;
    traceId: string;
    eventId: string;
    occurredAt: Date;
    organizationId: string;
    podId: string;
    actor: AgentMail.BrowserLifecycleActor;
    enrollmentId: string;
    credentialId: string;
}
