// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

/**
 * A body with `public_key` registers a public-key credential; any other
 * body mints a bearer key.
 */
export type CreateApiKeyRequest = AgentMail.CreateBearerApiKeyRequest | AgentMail.CreatePublicKeyRequest;
