// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

/**
 * An AgentID sign-in credential. `type` and `api_key_id` are server-owned;
 * use `api_key_id` as the JWS `kid`. This response never contains a bearer
 * secret or private key.
 */
export interface PublicKeyCredential {
    /** Server-generated credential ID. Store this value as the signing key's `kid`. */
    apiKeyId: string;
    /** Server-owned credential discriminator. Callers cannot select or update it. */
    type: "public_key";
    /** Human-readable credential name. */
    name: AgentMail.Name;
    publicKey: AgentMail.PublicKeyMaterial;
    scope: AgentMail.PublicKeyScope;
    /** Immutable absolute expiry. Omitted when the credential does not expire. */
    expiresAt?: Date;
    /** Present when organization-wide revoke-all invalidated this credential generation. */
    revokedAt?: Date;
    createdAt: Date;
    updatedAt: Date;
}
