// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

/**
 * Rename a credential or change its permissions. Key material, type,
 * scope, and expiry are immutable.
 */
export interface UpdateApiKeyRequest extends AgentMail.ApiKeyMutableFields {}
