/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { DomainId } from "./DomainId.js";
import { OrganizationId } from "../../../types/OrganizationId.js";
import { VerificationStatus } from "./VerificationStatus.js";
import { VerificationRecord } from "./VerificationRecord.js";

export const Domain: core.serialization.ObjectSchema<serializers.Domain.Raw, AgentMail.Domain> =
    core.serialization.object({
        domainId: core.serialization.property("domain_id", DomainId),
        organizationId: core.serialization.property("organization_id", OrganizationId),
        status: VerificationStatus,
        feedbackEnabled: core.serialization.property("feedback_enabled", core.serialization.boolean().optional()),
        records: core.serialization.list(VerificationRecord),
        updatedAt: core.serialization.property("updated_at", core.serialization.date()),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
    });

export declare namespace Domain {
    export interface Raw {
        domain_id: DomainId.Raw;
        organization_id: OrganizationId.Raw;
        status: VerificationStatus.Raw;
        feedback_enabled?: boolean | null;
        records: VerificationRecord.Raw[];
        updated_at: string;
        created_at: string;
    }
}
