// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const FeedbackEnabled: core.serialization.Schema<serializers.FeedbackEnabled.Raw, AgentMail.FeedbackEnabled> =
    core.serialization.boolean();

export declare namespace FeedbackEnabled {
    export type Raw = boolean;
}
