// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetSetupLinkResponse: core.serialization.ObjectSchema<
    serializers.GetSetupLinkResponse.Raw,
    AgentMail.GetSetupLinkResponse
> = core.serialization.object({
    supported: core.serialization.boolean(),
    providerName: core.serialization.property("provider_name", core.serialization.string().optional()),
    url: core.serialization.string().optional(),
    width: core.serialization.number().optional(),
    height: core.serialization.number().optional(),
    state: core.serialization.string().optional(),
    conflictingProvider: core.serialization.property("conflicting_provider", core.serialization.string().optional()),
});

export declare namespace GetSetupLinkResponse {
    export interface Raw {
        supported: boolean;
        provider_name?: string | null;
        url?: string | null;
        width?: number | null;
        height?: number | null;
        state?: string | null;
        conflicting_provider?: string | null;
    }
}
