// This file was auto-generated by Fern from our API Definition.

/**
 * Stable, machine-readable error code in snake_case (for example, not_found or missing_permission). Branch on this rather than the message text.
 */
export type ErrorCode = string;
