/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../index";

export interface ValidationErrorResponse {
    name: AgentMail.ErrorName;
    /** Validation errors. */
    errors?: unknown;
}
