// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../../../index.js";

/**
 * @example
 *     {
 *         timezone: "America/New_York"
 *     }
 */
export interface UpdateCalendarRequestWrapper extends AgentMail.UpdateCalendarRequest {
    /** The calendar's current `etag`, for example `"rv-0"`. Optional; makes the update conditional; `*` matches any current version. */
    ifMatch?: string;
}
