// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../../../index.js";

/**
 * @example
 *     {
 *         start: "2026-10-15T15:00:00",
 *         end: "2026-10-15T15:30:00",
 *         sendInvites: true
 *     }
 *
 * @example
 *     {
 *         mode: "single",
 *         start: "2026-10-07T10:00:00",
 *         end: "2026-10-07T10:15:00"
 *     }
 */
export interface UpdateCalendarEventRequestWrapper extends AgentMail.UpdateCalendarEventRequest {
    mode?: AgentMail.InstanceMutationMode;
    /** The event's or date's current `etag`, from the latest read or write response. Optional; makes the update conditional; `*` matches any current version. */
    ifMatch?: string;
}
