// This file was auto-generated by Fern from our API Definition.

/**
 * Allow inboxes on any subdomain of this domain. Adds a required wildcard MX
 * record (`*.<domain>`) to `records`.
 */
export type SubdomainsEnabled = boolean;
