// This file was auto-generated by Fern from our API Definition.

/**
 * Serve open tracking pixels from this domain. Adds a required `link.<domain>`
 * CNAME record to `records`, which must be published and verified before
 * `track_opens` can be used on a send.
 */
export type TrackingEnabled = boolean;
