// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

/**
 * Provide at least one of `feedback_enabled` or `subdomains_enabled`. Omitted
 * fields are left unchanged; an empty body is rejected. Enabling
 * `subdomains_enabled` on a verified domain returns it to `PENDING` until the
 * newly-required wildcard MX record (`*.<domain>`) is published and verified.
 */
export interface UpdateDomainRequest {
    feedbackEnabled?: AgentMail.FeedbackEnabled;
    subdomainsEnabled?: AgentMail.SubdomainsEnabled;
}
