// This file was auto-generated by Fern from our API Definition.

/** The scope tier the authenticated credential is bound to. */
export const ScopeType = {
    Organization: "organization",
    Pod: "pod",
    Inbox: "inbox",
} as const;
export type ScopeType = (typeof ScopeType)[keyof typeof ScopeType];
