/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../../../../../index.js";

export interface Bounce {
    inbox_id: AgentMail.inboxes.InboxId;
    message_id: AgentMail.MessageId;
    timestamp: AgentMail.webhooks.Timestamp;
    /** Bounce type. */
    type: string;
    /** Bounce sub-type. */
    sub_type: string;
    /** Bounced recipients. */
    recipients: AgentMail.webhooks.Recipient[];
}
