/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../../../../../index.js";

export interface MessageSentPayload {
    event_type: AgentMail.webhooks.EventType;
    event_id: AgentMail.webhooks.EventId;
    send: AgentMail.webhooks.Send;
}
