/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../../../../../index";

export interface MessageReceivedPayload {
    eventType: AgentMail.webhooks.EventType;
    eventId: AgentMail.webhooks.EventId;
    message: AgentMail.Message;
}
