/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const InboxIds: core.serialization.Schema<serializers.webhooks.InboxIds.Raw, AgentMail.webhooks.InboxIds> =
    core.serialization.list(core.serialization.string());

export declare namespace InboxIds {
    export type Raw = string[];
}
