/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";
import { EventType } from "./EventType";
import { EventId } from "./EventId";

export const Payload: core.serialization.ObjectSchema<serializers.Payload.Raw, AgentMail.Payload> =
    core.serialization.object({
        eventType: core.serialization.property("event_type", EventType),
        eventId: core.serialization.property("event_id", EventId),
    });

export declare namespace Payload {
    export interface Raw {
        event_type: EventType.Raw;
        event_id: EventId.Raw;
    }
}
