// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { InboxIds } from "../../events/types/InboxIds.js";
import { PodIds } from "../../events/types/PodIds.js";

export const UpdateWebhookRequest: core.serialization.ObjectSchema<
    serializers.webhooks.UpdateWebhookRequest.Raw,
    AgentMail.webhooks.UpdateWebhookRequest
> = core.serialization.object({
    addInboxIds: core.serialization.property("add_inbox_ids", InboxIds.optional()),
    removeInboxIds: core.serialization.property("remove_inbox_ids", InboxIds.optional()),
    addPodIds: core.serialization.property("add_pod_ids", PodIds.optional()),
    removePodIds: core.serialization.property("remove_pod_ids", PodIds.optional()),
});

export declare namespace UpdateWebhookRequest {
    export interface Raw {
        add_inbox_ids?: InboxIds.Raw | null;
        remove_inbox_ids?: InboxIds.Raw | null;
        add_pod_ids?: PodIds.Raw | null;
        remove_pod_ids?: PodIds.Raw | null;
    }
}
