/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as AgentMail from "../../../../api/index";
import * as core from "../../../../core";

export const Url: core.serialization.Schema<serializers.webhooks.Url.Raw, AgentMail.webhooks.Url> =
    core.serialization.string();

export declare namespace Url {
    export type Raw = string;
}
