/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as AgentMail from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const MessageReferences: core.serialization.Schema<
    serializers.inboxes.MessageReferences.Raw,
    AgentMail.inboxes.MessageReferences
> = core.serialization.list(core.serialization.string());

export declare namespace MessageReferences {
    export type Raw = string[];
}
