/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as AgentMail from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const UpdateMessageRequest: core.serialization.ObjectSchema<
    serializers.inboxes.UpdateMessageRequest.Raw,
    AgentMail.inboxes.UpdateMessageRequest
> = core.serialization.object({
    addLabels: core.serialization.property(
        "add_labels",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    removeLabels: core.serialization.property(
        "remove_labels",
        core.serialization.list(core.serialization.string()).optional(),
    ),
});

export declare namespace UpdateMessageRequest {
    export interface Raw {
        add_labels?: string[] | null;
        remove_labels?: string[] | null;
    }
}
