/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../../../index";

export interface ThreadItem {
    threadId: AgentMail.ThreadId;
    updatedAt: AgentMail.ThreadUpdatedAt;
    participants: AgentMail.ThreadParticipants;
    messageCount: AgentMail.ThreadMessageCount;
    subject?: AgentMail.ThreadSubject;
    preview?: AgentMail.ThreadPreview;
    attachments?: AgentMail.ThreadAttachments;
}
