/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../../../index";

export interface ThreadAttachment {
    /** Message ID of attachment. */
    messageId: string;
    attachmentId: AgentMail.AttachmentId;
    filename: AgentMail.AttachmentFilename;
    contentType: AgentMail.AttachmentContentType;
    size: AgentMail.AttachmentSize;
    inline: AgentMail.AttachmentInline;
}
