/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentmailApi from "../../../index";

export interface Thread {
    threadId: AgentmailApi.ThreadId;
    inboxId: AgentmailApi.InboxId;
    /** Time at which thread was created. */
    createdAt: Date;
    updatedAt: AgentmailApi.ThreadUpdatedAt;
    subject?: AgentmailApi.ThreadSubject;
    participants: AgentmailApi.ThreadParticipants;
    /** Messages in thread. Ordered by `sent_at` ascending. */
    messages: AgentmailApi.Message[];
}
