// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

/**
 * Attachments in draft.
 */
export type DraftAttachments = AgentMail.Attachment[];
