/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AgentMail from "../../../index";

/**
 * @example
 *     {
 *         drafts: [{
 *                 inboxId: "yourinbox@agentmail.to",
 *                 threadId: "thread_123",
 *                 draftId: "draft_123",
 *                 eventId: "event_123",
 *                 labels: ["RECEIVED", "UNREAD"],
 *                 updatedAt: "2024-01-15T09:30:00Z",
 *                 createdAt: "2024-01-15T09:30:00Z",
 *                 to: ["bob@example.com"],
 *                 subject: "Project Discussion",
 *                 preview: "Let's review the timeline for the project.",
 *                 cc: ["charlie@example.com"],
 *                 bcc: ["david@example.com"],
 *                 attachments: [{
 *                         attachmentId: "att_123",
 *                         filename: "proposal.pdf",
 *                         contentType: "application/pdf",
 *                         size: 1024,
 *                         inline: false
 *                     }]
 *             }, {
 *                 inboxId: "yourinbox@agentmail.to",
 *                 threadId: "thread_123",
 *                 draftId: "draft_456",
 *                 eventId: "event_456",
 *                 labels: ["SENT"],
 *                 updatedAt: "2024-01-15T10:15:00Z",
 *                 createdAt: "2024-01-15T10:15:00Z",
 *                 to: ["alice@example.com"],
 *                 subject: "Re: Project Discussion",
 *                 preview: "Sounds good, let's meet tomorrow."
 *             }],
 *         limit: 10,
 *         count: 2,
 *         lastKey: "draft_456#2024-01-15T10:15:00Z"
 *     }
 */
export interface ListDraftsResponse {
    count: AgentMail.Count;
    limit?: AgentMail.Limit;
    lastKey?: AgentMail.LastKey;
    /** Draft items. Ordered by `updated_at` descending. */
    drafts: AgentMail.DraftItem[];
}
