// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const CreateListEntryRequest: core.serialization.ObjectSchema<
    serializers.CreateListEntryRequest.Raw,
    AgentMail.CreateListEntryRequest
> = core.serialization.object({
    entry: core.serialization.string(),
    reason: core.serialization.string().optional(),
});

export declare namespace CreateListEntryRequest {
    export interface Raw {
        entry: string;
        reason?: string | null;
    }
}
