// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const Direction: core.serialization.Schema<serializers.Direction.Raw, AgentMail.Direction> =
    core.serialization.enum_(["send", "receive"]);

export declare namespace Direction {
    export type Raw = "send" | "receive";
}
