// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ListEntryBase } from "./ListEntryBase.js";

export const ListEntry: core.serialization.ObjectSchema<serializers.ListEntry.Raw, AgentMail.ListEntry> =
    core.serialization.object({}).extend(ListEntryBase);

export declare namespace ListEntry {
    export interface Raw extends ListEntryBase.Raw {}
}
