// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ListEntryBase } from "./ListEntryBase.js";

export const PodListEntry: core.serialization.ObjectSchema<serializers.PodListEntry.Raw, AgentMail.PodListEntry> =
    core.serialization
        .object({
            podId: core.serialization.property("pod_id", core.serialization.string()),
            inboxId: core.serialization.property("inbox_id", core.serialization.string().optional()),
        })
        .extend(ListEntryBase);

export declare namespace PodListEntry {
    export interface Raw extends ListEntryBase.Raw {
        pod_id: string;
        inbox_id?: string | null;
    }
}
