/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as AgentMail from "../../api/index.js";
import * as core from "../../core/index.js";

export const Before: core.serialization.Schema<serializers.Before.Raw, AgentMail.Before> = core.serialization.date();

export declare namespace Before {
    export type Raw = string;
}
