/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as AgentMail from "../../api/index";
import * as core from "../../core";

export const Labels: core.serialization.Schema<serializers.Labels.Raw, AgentMail.Labels> = core.serialization.list(
    core.serialization.string(),
);

export declare namespace Labels {
    export type Raw = string[];
}
