/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as AgentMail from "../../api/index";
import * as core from "../../core";

export const PageToken: core.serialization.Schema<serializers.PageToken.Raw, AgentMail.PageToken> =
    core.serialization.string();

export declare namespace PageToken {
    export type Raw = string;
}
