/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as AgentmailApi from "../../api/index";
import * as core from "../../core";
import { ErrorName } from "./ErrorName";

export const ValidationErrorResponse: core.serialization.ObjectSchema<
    serializers.ValidationErrorResponse.Raw,
    AgentmailApi.ValidationErrorResponse
> = core.serialization.object({
    name: ErrorName,
    errors: core.serialization.unknown(),
});

export declare namespace ValidationErrorResponse {
    export interface Raw {
        name: ErrorName.Raw;
        errors?: unknown;
    }
}
