// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListMessagesRequest {
    limit?: AgentMail.Limit;
    pageToken?: AgentMail.PageToken;
    labels?: AgentMail.Labels;
    before?: AgentMail.Before;
    after?: AgentMail.After;
    ascending?: AgentMail.Ascending;
}
