// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import type * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ConnectProviderBody } from "../types/ConnectProviderBody.js";

export const Request: core.serialization.Schema<
    serializers.providers.connect.Request.Raw,
    AgentMail.ConnectProviderBody | undefined
> = ConnectProviderBody.optional();

export declare namespace Request {
    export type Raw = ConnectProviderBody.Raw | null | undefined;
}
