// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

/**
 * Authorize one pending AgentID sign-in for the inbox in the path. The
 * inbox is selected by the trusted path parameter, never by an AgentID
 * `login_hint`.
 */
export interface AuthorizeInboxRequest {
    authToken: AgentMail.AuthToken;
    acceptDisclosure?: AgentMail.AcceptDisclosure;
}
