// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

export interface UpdateInboxRequest {
    displayName: AgentMail.inboxes.DisplayName;
}
