// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ProviderId } from "../../accounts/types/ProviderId.js";

export const Provider: core.serialization.ObjectSchema<serializers.Provider.Raw, AgentMail.Provider> =
    core.serialization.object({
        providerId: core.serialization.property("provider_id", ProviderId),
        name: core.serialization.string().optional(),
        updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
        description: core.serialization.string().optional(),
        logoUrl: core.serialization.property("logo_url", core.serialization.string().optional()),
        termsUrl: core.serialization.property("terms_url", core.serialization.string().optional()),
        privacyUrl: core.serialization.property("privacy_url", core.serialization.string().optional()),
    });

export declare namespace Provider {
    export interface Raw {
        provider_id: ProviderId.Raw;
        name?: string | null;
        updated_at?: string | null;
        description?: string | null;
        logo_url?: string | null;
        terms_url?: string | null;
        privacy_url?: string | null;
    }
}
