// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { AppCategory } from "./AppCategory.js";
import { AppId } from "./AppId.js";

export const App: core.serialization.ObjectSchema<serializers.App.Raw, AgentMail.App> = core.serialization.object({
    appId: core.serialization.property("app_id", AppId),
    name: core.serialization.string().optional(),
    updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
    description: core.serialization.string().optional(),
    logoUrl: core.serialization.property("logo_url", core.serialization.string().optional()),
    termsUrl: core.serialization.property("terms_url", core.serialization.string().optional()),
    privacyUrl: core.serialization.property("privacy_url", core.serialization.string().optional()),
    categories: core.serialization.list(AppCategory).optional(),
    ownerSignupLimit: core.serialization.property("owner_signup_limit", core.serialization.number().optional()),
});

export declare namespace App {
    export interface Raw {
        app_id: AppId.Raw;
        name?: string | null;
        updated_at?: string | null;
        description?: string | null;
        logo_url?: string | null;
        terms_url?: string | null;
        privacy_url?: string | null;
        categories?: AppCategory.Raw[] | null;
        owner_signup_limit?: number | null;
    }
}
