// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const AppCategory: core.serialization.Schema<serializers.AppCategory.Raw, AgentMail.AppCategory> =
    core.serialization.enum_([
        "ai",
        "search",
        "scraping",
        "browser",
        "data",
        "developer-tools",
        "communication",
        "productivity",
        "payments",
        "finance",
        "commerce",
        "marketing",
        "analytics",
        "security",
        "infrastructure",
        "other",
    ]);

export declare namespace AppCategory {
    export type Raw =
        | "ai"
        | "search"
        | "scraping"
        | "browser"
        | "data"
        | "developer-tools"
        | "communication"
        | "productivity"
        | "payments"
        | "finance"
        | "commerce"
        | "marketing"
        | "analytics"
        | "security"
        | "infrastructure"
        | "other";
}
