// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { AcceptDisclosure } from "../../apiKeys/types/AcceptDisclosure.js";
import { ConnectInboxId } from "./ConnectInboxId.js";

export const ConnectAppBody: core.serialization.ObjectSchema<serializers.ConnectAppBody.Raw, AgentMail.ConnectAppBody> =
    core.serialization.object({
        inboxId: core.serialization.property("inbox_id", ConnectInboxId.optional()),
        acceptDisclosure: core.serialization.property("accept_disclosure", AcceptDisclosure.optional()),
    });

export declare namespace ConnectAppBody {
    export interface Raw {
        inbox_id?: ConnectInboxId.Raw | null;
        accept_disclosure?: AcceptDisclosure.Raw | null;
    }
}
