// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ApiKeyPermissions: core.serialization.ObjectSchema<
    serializers.ApiKeyPermissions.Raw,
    AgentMail.ApiKeyPermissions
> = core.serialization.object({
    inboxRead: core.serialization.property("inbox_read", core.serialization.boolean().optional()),
    inboxCreate: core.serialization.property("inbox_create", core.serialization.boolean().optional()),
    inboxUpdate: core.serialization.property("inbox_update", core.serialization.boolean().optional()),
    inboxDelete: core.serialization.property("inbox_delete", core.serialization.boolean().optional()),
    threadRead: core.serialization.property("thread_read", core.serialization.boolean().optional()),
    threadDelete: core.serialization.property("thread_delete", core.serialization.boolean().optional()),
    messageRead: core.serialization.property("message_read", core.serialization.boolean().optional()),
    messageSend: core.serialization.property("message_send", core.serialization.boolean().optional()),
    messageUpdate: core.serialization.property("message_update", core.serialization.boolean().optional()),
    labelSpamRead: core.serialization.property("label_spam_read", core.serialization.boolean().optional()),
    labelBlockedRead: core.serialization.property("label_blocked_read", core.serialization.boolean().optional()),
    labelTrashRead: core.serialization.property("label_trash_read", core.serialization.boolean().optional()),
    draftRead: core.serialization.property("draft_read", core.serialization.boolean().optional()),
    draftCreate: core.serialization.property("draft_create", core.serialization.boolean().optional()),
    draftUpdate: core.serialization.property("draft_update", core.serialization.boolean().optional()),
    draftDelete: core.serialization.property("draft_delete", core.serialization.boolean().optional()),
    draftSend: core.serialization.property("draft_send", core.serialization.boolean().optional()),
    webhookRead: core.serialization.property("webhook_read", core.serialization.boolean().optional()),
    webhookCreate: core.serialization.property("webhook_create", core.serialization.boolean().optional()),
    webhookUpdate: core.serialization.property("webhook_update", core.serialization.boolean().optional()),
    webhookDelete: core.serialization.property("webhook_delete", core.serialization.boolean().optional()),
    domainRead: core.serialization.property("domain_read", core.serialization.boolean().optional()),
    domainCreate: core.serialization.property("domain_create", core.serialization.boolean().optional()),
    domainUpdate: core.serialization.property("domain_update", core.serialization.boolean().optional()),
    domainDelete: core.serialization.property("domain_delete", core.serialization.boolean().optional()),
    listEntryRead: core.serialization.property("list_entry_read", core.serialization.boolean().optional()),
    listEntryCreate: core.serialization.property("list_entry_create", core.serialization.boolean().optional()),
    listEntryDelete: core.serialization.property("list_entry_delete", core.serialization.boolean().optional()),
    metricsRead: core.serialization.property("metrics_read", core.serialization.boolean().optional()),
    apiKeyRead: core.serialization.property("api_key_read", core.serialization.boolean().optional()),
    apiKeyCreate: core.serialization.property("api_key_create", core.serialization.boolean().optional()),
    apiKeyDelete: core.serialization.property("api_key_delete", core.serialization.boolean().optional()),
    podRead: core.serialization.property("pod_read", core.serialization.boolean().optional()),
    podCreate: core.serialization.property("pod_create", core.serialization.boolean().optional()),
    podDelete: core.serialization.property("pod_delete", core.serialization.boolean().optional()),
});

export declare namespace ApiKeyPermissions {
    export interface Raw {
        inbox_read?: boolean | null;
        inbox_create?: boolean | null;
        inbox_update?: boolean | null;
        inbox_delete?: boolean | null;
        thread_read?: boolean | null;
        thread_delete?: boolean | null;
        message_read?: boolean | null;
        message_send?: boolean | null;
        message_update?: boolean | null;
        label_spam_read?: boolean | null;
        label_blocked_read?: boolean | null;
        label_trash_read?: boolean | null;
        draft_read?: boolean | null;
        draft_create?: boolean | null;
        draft_update?: boolean | null;
        draft_delete?: boolean | null;
        draft_send?: boolean | null;
        webhook_read?: boolean | null;
        webhook_create?: boolean | null;
        webhook_update?: boolean | null;
        webhook_delete?: boolean | null;
        domain_read?: boolean | null;
        domain_create?: boolean | null;
        domain_update?: boolean | null;
        domain_delete?: boolean | null;
        list_entry_read?: boolean | null;
        list_entry_create?: boolean | null;
        list_entry_delete?: boolean | null;
        metrics_read?: boolean | null;
        api_key_read?: boolean | null;
        api_key_create?: boolean | null;
        api_key_delete?: boolean | null;
        pod_read?: boolean | null;
        pod_create?: boolean | null;
        pod_delete?: boolean | null;
    }
}
