/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const ApiKeyId: core.serialization.Schema<serializers.ApiKeyId.Raw, AgentMail.ApiKeyId> =
    core.serialization.string();

export declare namespace ApiKeyId {
    export type Raw = string;
}
