// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ApiKeyPermissions: core.serialization.ObjectSchema<
    serializers.ApiKeyPermissions.Raw,
    AgentMail.ApiKeyPermissions
> = core.serialization.object({
    readInbox: core.serialization.property("read_inbox", core.serialization.boolean().optional()),
    createInbox: core.serialization.property("create_inbox", core.serialization.boolean().optional()),
    updateInbox: core.serialization.property("update_inbox", core.serialization.boolean().optional()),
    deleteInbox: core.serialization.property("delete_inbox", core.serialization.boolean().optional()),
    readThread: core.serialization.property("read_thread", core.serialization.boolean().optional()),
    deleteThread: core.serialization.property("delete_thread", core.serialization.boolean().optional()),
    readMessage: core.serialization.property("read_message", core.serialization.boolean().optional()),
    sendMessage: core.serialization.property("send_message", core.serialization.boolean().optional()),
    updateMessage: core.serialization.property("update_message", core.serialization.boolean().optional()),
    readSpam: core.serialization.property("read_spam", core.serialization.boolean().optional()),
    readBlocked: core.serialization.property("read_blocked", core.serialization.boolean().optional()),
    readTrash: core.serialization.property("read_trash", core.serialization.boolean().optional()),
    readDraft: core.serialization.property("read_draft", core.serialization.boolean().optional()),
    createDraft: core.serialization.property("create_draft", core.serialization.boolean().optional()),
    updateDraft: core.serialization.property("update_draft", core.serialization.boolean().optional()),
    deleteDraft: core.serialization.property("delete_draft", core.serialization.boolean().optional()),
    sendDraft: core.serialization.property("send_draft", core.serialization.boolean().optional()),
    readWebhook: core.serialization.property("read_webhook", core.serialization.boolean().optional()),
    createWebhook: core.serialization.property("create_webhook", core.serialization.boolean().optional()),
    updateWebhook: core.serialization.property("update_webhook", core.serialization.boolean().optional()),
    deleteWebhook: core.serialization.property("delete_webhook", core.serialization.boolean().optional()),
    readDomain: core.serialization.property("read_domain", core.serialization.boolean().optional()),
    createDomain: core.serialization.property("create_domain", core.serialization.boolean().optional()),
    updateDomain: core.serialization.property("update_domain", core.serialization.boolean().optional()),
    deleteDomain: core.serialization.property("delete_domain", core.serialization.boolean().optional()),
    readListEntry: core.serialization.property("read_list_entry", core.serialization.boolean().optional()),
    createListEntry: core.serialization.property("create_list_entry", core.serialization.boolean().optional()),
    deleteListEntry: core.serialization.property("delete_list_entry", core.serialization.boolean().optional()),
    readMetrics: core.serialization.property("read_metrics", core.serialization.boolean().optional()),
    readApiKey: core.serialization.property("read_api_key", core.serialization.boolean().optional()),
    createApiKey: core.serialization.property("create_api_key", core.serialization.boolean().optional()),
    deleteApiKey: core.serialization.property("delete_api_key", core.serialization.boolean().optional()),
    readPod: core.serialization.property("read_pod", core.serialization.boolean().optional()),
    createPod: core.serialization.property("create_pod", core.serialization.boolean().optional()),
    deletePod: core.serialization.property("delete_pod", core.serialization.boolean().optional()),
});

export declare namespace ApiKeyPermissions {
    export interface Raw {
        read_inbox?: boolean | null;
        create_inbox?: boolean | null;
        update_inbox?: boolean | null;
        delete_inbox?: boolean | null;
        read_thread?: boolean | null;
        delete_thread?: boolean | null;
        read_message?: boolean | null;
        send_message?: boolean | null;
        update_message?: boolean | null;
        read_spam?: boolean | null;
        read_blocked?: boolean | null;
        read_trash?: boolean | null;
        read_draft?: boolean | null;
        create_draft?: boolean | null;
        update_draft?: boolean | null;
        delete_draft?: boolean | null;
        send_draft?: boolean | null;
        read_webhook?: boolean | null;
        create_webhook?: boolean | null;
        update_webhook?: boolean | null;
        delete_webhook?: boolean | null;
        read_domain?: boolean | null;
        create_domain?: boolean | null;
        update_domain?: boolean | null;
        delete_domain?: boolean | null;
        read_list_entry?: boolean | null;
        create_list_entry?: boolean | null;
        delete_list_entry?: boolean | null;
        read_metrics?: boolean | null;
        read_api_key?: boolean | null;
        create_api_key?: boolean | null;
        delete_api_key?: boolean | null;
        read_pod?: boolean | null;
        create_pod?: boolean | null;
        delete_pod?: boolean | null;
    }
}
