// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { ApiKeyId } from "./ApiKeyId.js";
import { ApiKeyPermissions } from "./ApiKeyPermissions.js";
import { CreatedAt } from "./CreatedAt.js";
import { ExpiresAt } from "./ExpiresAt.js";
import { InboxScopeId } from "./InboxScopeId.js";
import { Name } from "./Name.js";
import { PodScopeId } from "./PodScopeId.js";
import { Prefix } from "./Prefix.js";
import { UpdatedAt } from "./UpdatedAt.js";
import { UsedAt } from "./UsedAt.js";

export const BearerApiKey: core.serialization.ObjectSchema<serializers.BearerApiKey.Raw, AgentMail.BearerApiKey> =
    core.serialization.object({
        type: core.serialization.stringLiteral("bearer"),
        apiKeyId: core.serialization.property("api_key_id", ApiKeyId),
        prefix: Prefix,
        name: Name,
        podId: core.serialization.property("pod_id", PodScopeId.optional()),
        inboxId: core.serialization.property("inbox_id", InboxScopeId.optional()),
        usedAt: core.serialization.property("used_at", UsedAt.optional()),
        permissions: ApiKeyPermissions.optional(),
        createdAt: core.serialization.property("created_at", CreatedAt),
        updatedAt: core.serialization.property("updated_at", UpdatedAt),
        expiresAt: core.serialization.property("expires_at", ExpiresAt.optional()),
    });

export declare namespace BearerApiKey {
    export interface Raw {
        type: "bearer";
        api_key_id: ApiKeyId.Raw;
        prefix: Prefix.Raw;
        name: Name.Raw;
        pod_id?: PodScopeId.Raw | null;
        inbox_id?: InboxScopeId.Raw | null;
        used_at?: UsedAt.Raw | null;
        permissions?: ApiKeyPermissions.Raw | null;
        created_at: CreatedAt.Raw;
        updated_at: UpdatedAt.Raw;
        expires_at?: ExpiresAt.Raw | null;
    }
}
