// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const BrowserCredentialCreator: core.serialization.ObjectSchema<
    serializers.BrowserCredentialCreator.Raw,
    AgentMail.BrowserCredentialCreator
> = core.serialization.object({
    kind: core.serialization.stringLiteral("bearer_api_key"),
    apiKeyId: core.serialization.property("api_key_id", core.serialization.string()),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
});

export declare namespace BrowserCredentialCreator {
    export interface Raw {
        kind: "bearer_api_key";
        api_key_id: string;
        created_at: string;
    }
}
