// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { BrowserConsentLifecycleEventType } from "./BrowserConsentLifecycleEventType.js";
import { BrowserLifecycleActor } from "./BrowserLifecycleActor.js";

export const BrowserConsentLifecycleEvent: core.serialization.ObjectSchema<
    serializers.BrowserConsentLifecycleEvent.Raw,
    AgentMail.BrowserConsentLifecycleEvent
> = core.serialization.object({
    type: BrowserConsentLifecycleEventType,
    traceId: core.serialization.property("trace_id", core.serialization.string()),
    eventId: core.serialization.property("event_id", core.serialization.string()),
    occurredAt: core.serialization.property("occurred_at", core.serialization.date()),
    organizationId: core.serialization.property("organization_id", core.serialization.string()),
    podId: core.serialization.property("pod_id", core.serialization.string()),
    actor: BrowserLifecycleActor,
    consentId: core.serialization.property("consent_id", core.serialization.string()),
    clientType: core.serialization.property("client_type", core.serialization.stringLiteral("closed")),
    clientId: core.serialization.property("client_id", core.serialization.string()),
});

export declare namespace BrowserConsentLifecycleEvent {
    export interface Raw {
        type: BrowserConsentLifecycleEventType.Raw;
        trace_id: string;
        event_id: string;
        occurred_at: string;
        organization_id: string;
        pod_id: string;
        actor: BrowserLifecycleActor.Raw;
        consent_id: string;
        client_type: "closed";
        client_id: string;
    }
}
