// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const PodScopeId: core.serialization.Schema<serializers.PodScopeId.Raw, AgentMail.PodScopeId> =
    core.serialization.string();

export declare namespace PodScopeId {
    export type Raw = string;
}
