// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { InboxPublicKeyScope } from "./InboxPublicKeyScope.js";
import { OrganizationPublicKeyScope } from "./OrganizationPublicKeyScope.js";
import { PodPublicKeyScope } from "./PodPublicKeyScope.js";

export const PublicKeyScope: core.serialization.Schema<serializers.PublicKeyScope.Raw, AgentMail.PublicKeyScope> =
    core.serialization
        .union("type", {
            organization: OrganizationPublicKeyScope,
            pod: PodPublicKeyScope,
            inbox: InboxPublicKeyScope,
        })
        .transform<AgentMail.PublicKeyScope>({
            transform: (value) => value,
            untransform: (value) => value,
        });

export declare namespace PublicKeyScope {
    export type Raw = PublicKeyScope.Organization | PublicKeyScope.Pod | PublicKeyScope.Inbox;

    export interface Organization extends OrganizationPublicKeyScope.Raw {
        type: "organization";
    }

    export interface Pod extends PodPublicKeyScope.Raw {
        type: "pod";
    }

    export interface Inbox extends InboxPublicKeyScope.Raw {
        type: "inbox";
    }
}
