// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const RevokeAllAgentIdSignInKeysResponse: core.serialization.ObjectSchema<
    serializers.RevokeAllAgentIdSignInKeysResponse.Raw,
    AgentMail.RevokeAllAgentIdSignInKeysResponse
> = core.serialization.object({
    previousGeneration: core.serialization.property("previous_generation", core.serialization.number()),
    currentGeneration: core.serialization.property("current_generation", core.serialization.number()),
    revokedAt: core.serialization.property("revoked_at", core.serialization.date()),
});

export declare namespace RevokeAllAgentIdSignInKeysResponse {
    export interface Raw {
        previous_generation: number;
        current_generation: number;
        revoked_at: string;
    }
}
