/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { AgentMailClient } from "../../src/Client";

describe("Drafts", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = {
            count: 1,
            limit: 1,
            next_page_token: "next_page_token",
            drafts: [
                {
                    inbox_id: "inbox_id",
                    thread_id: "thread_id",
                    draft_id: "draft_id",
                    labels: ["labels", "labels"],
                    to: ["to", "to"],
                    cc: ["cc", "cc"],
                    bcc: ["bcc", "bcc"],
                    subject: "subject",
                    preview: "preview",
                    attachments: [
                        {
                            attachment_id: "attachment_id",
                            filename: "filename",
                            content_type: "content_type",
                            size: 1,
                            inline: true,
                        },
                        {
                            attachment_id: "attachment_id",
                            filename: "filename",
                            content_type: "content_type",
                            size: 1,
                            inline: true,
                        },
                    ],
                    send_status: "scheduled",
                    send_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
                {
                    inbox_id: "inbox_id",
                    thread_id: "thread_id",
                    draft_id: "draft_id",
                    labels: ["labels", "labels"],
                    to: ["to", "to"],
                    cc: ["cc", "cc"],
                    bcc: ["bcc", "bcc"],
                    subject: "subject",
                    preview: "preview",
                    attachments: [
                        {
                            attachment_id: "attachment_id",
                            filename: "filename",
                            content_type: "content_type",
                            size: 1,
                            inline: true,
                        },
                        {
                            attachment_id: "attachment_id",
                            filename: "filename",
                            content_type: "content_type",
                            size: 1,
                            inline: true,
                        },
                    ],
                    send_status: "scheduled",
                    send_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
        };
        server.mockEndpoint().get("/v0/drafts").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.drafts.list();
        expect(response).toEqual({
            count: 1,
            limit: 1,
            nextPageToken: "next_page_token",
            drafts: [
                {
                    inboxId: "inbox_id",
                    threadId: "thread_id",
                    draftId: "draft_id",
                    labels: ["labels", "labels"],
                    to: ["to", "to"],
                    cc: ["cc", "cc"],
                    bcc: ["bcc", "bcc"],
                    subject: "subject",
                    preview: "preview",
                    attachments: [
                        {
                            attachmentId: "attachment_id",
                            filename: "filename",
                            contentType: "content_type",
                            size: 1,
                            inline: true,
                        },
                        {
                            attachmentId: "attachment_id",
                            filename: "filename",
                            contentType: "content_type",
                            size: 1,
                            inline: true,
                        },
                    ],
                    sendStatus: "scheduled",
                    sendAt: new Date("2024-01-15T09:30:00.000Z"),
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                },
                {
                    inboxId: "inbox_id",
                    threadId: "thread_id",
                    draftId: "draft_id",
                    labels: ["labels", "labels"],
                    to: ["to", "to"],
                    cc: ["cc", "cc"],
                    bcc: ["bcc", "bcc"],
                    subject: "subject",
                    preview: "preview",
                    attachments: [
                        {
                            attachmentId: "attachment_id",
                            filename: "filename",
                            contentType: "content_type",
                            size: 1,
                            inline: true,
                        },
                        {
                            attachmentId: "attachment_id",
                            filename: "filename",
                            contentType: "content_type",
                            size: 1,
                            inline: true,
                        },
                    ],
                    sendStatus: "scheduled",
                    sendAt: new Date("2024-01-15T09:30:00.000Z"),
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                },
            ],
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new AgentMailClient({
            apiKey: "test",
            environment: { http: server.baseUrl, websockets: server.baseUrl },
        });

        const rawResponseBody = {
            inbox_id: "inbox_id",
            thread_id: "thread_id",
            draft_id: "draft_id",
            labels: ["labels", "labels"],
            reply_to: ["reply_to", "reply_to"],
            to: ["to", "to"],
            cc: ["cc", "cc"],
            bcc: ["bcc", "bcc"],
            subject: "subject",
            preview: "preview",
            text: "text",
            html: "html",
            attachments: [
                {
                    attachment_id: "attachment_id",
                    filename: "filename",
                    content_type: "content_type",
                    size: 1,
                    inline: true,
                },
                {
                    attachment_id: "attachment_id",
                    filename: "filename",
                    content_type: "content_type",
                    size: 1,
                    inline: true,
                },
            ],
            in_reply_to: "in_reply_to",
            references: ["references", "references"],
            send_status: "scheduled",
            send_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            created_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .get("/v0/drafts/draft_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.drafts.get("draft_id");
        expect(response).toEqual({
            inboxId: "inbox_id",
            threadId: "thread_id",
            draftId: "draft_id",
            labels: ["labels", "labels"],
            replyTo: ["reply_to", "reply_to"],
            to: ["to", "to"],
            cc: ["cc", "cc"],
            bcc: ["bcc", "bcc"],
            subject: "subject",
            preview: "preview",
            text: "text",
            html: "html",
            attachments: [
                {
                    attachmentId: "attachment_id",
                    filename: "filename",
                    contentType: "content_type",
                    size: 1,
                    inline: true,
                },
                {
                    attachmentId: "attachment_id",
                    filename: "filename",
                    contentType: "content_type",
                    size: 1,
                    inline: true,
                },
            ],
            inReplyTo: "in_reply_to",
            references: ["references", "references"],
            sendStatus: "scheduled",
            sendAt: new Date("2024-01-15T09:30:00.000Z"),
            updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            createdAt: new Date("2024-01-15T09:30:00.000Z"),
        });
    });
});
