// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../index.js";

/**
 * An app an inbox can sign in to.
 */
export interface App {
    appId: AgentMail.AppId;
    name?: string;
    /** Time at which app was last updated. */
    updatedAt?: Date;
    description?: string;
    logoUrl?: string;
    termsUrl?: string;
    privacyUrl?: string;
    /** Maximum number of accounts your organization may sign up at this app. Omitted when the app sets no limit. 0 means the app has paused new sign-ups; existing accounts keep signing in. */
    ownerSignupLimit?: number;
}
