// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const InboxEventType: core.serialization.Schema<serializers.InboxEventType.Raw, AgentMail.InboxEventType> =
    core.serialization.enum_(["label.added", "label.removed"]);

export declare namespace InboxEventType {
    export type Raw = "label.added" | "label.removed";
}
