/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const AgentMailApiEnvironment = {
    Production: "https://api.agentmail.to",
} as const;

export type AgentMailApiEnvironment = typeof AgentMailApiEnvironment.Production;
