// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const End: core.serialization.Schema<serializers.End.Raw, AgentMail.End> = core.serialization.date();

export declare namespace End {
    export type Raw = string;
}
