/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const MetricTimestamp: core.serialization.Schema<serializers.MetricTimestamp.Raw, AgentMail.MetricTimestamp> =
    core.serialization.date();

export declare namespace MetricTimestamp {
    export type Raw = string;
}
