/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const AttachmentContent: core.serialization.Schema<
    serializers.AttachmentContent.Raw,
    AgentMail.AttachmentContent
> = core.serialization.string();

export declare namespace AttachmentContent {
    export type Raw = string;
}
