// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const AttachmentContentId: core.serialization.Schema<
    serializers.AttachmentContentId.Raw,
    AgentMail.AttachmentContentId
> = core.serialization.string();

export declare namespace AttachmentContentId {
    export type Raw = string;
}
