// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const AttachmentInline: core.serialization.Schema<serializers.AttachmentInline.Raw, AgentMail.AttachmentInline> =
    core.serialization.boolean();

export declare namespace AttachmentInline {
    export type Raw = boolean;
}
