/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const AttachmentId: core.serialization.Schema<serializers.AttachmentId.Raw, AgentMail.AttachmentId> =
    core.serialization.string();

export declare namespace AttachmentId {
    export type Raw = string;
}
