// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const AttachmentSize: core.serialization.Schema<serializers.AttachmentSize.Raw, AgentMail.AttachmentSize> =
    core.serialization.number();

export declare namespace AttachmentSize {
    export type Raw = number;
}
