// This file was auto-generated by Fern from our API Definition.

import type * as AgentMail from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const AccountStatus: core.serialization.Schema<serializers.AccountStatus.Raw, AgentMail.AccountStatus> =
    core.serialization.enum_(["disabled"]);

export declare namespace AccountStatus {
    export type Raw = "disabled";
}
